viur-framework/viur-core

config.py
modules/user.py
utils.py

This PR contains improvements of the utils.
Your're welcome to add your related stuff here.

WIP: improve utils

---

skeleton.py

relations would not update as the key was not correctly passed

fixed bug in updateRelations

---

modules/user.py

This piece of code didn't work when a project used a modified userpassword authentication flow. This fixes it.

Check for userpassword authentication on auth method name

---

bones/bone.py
bones/numericBone.py
bones/relationalBone.py
bones/stringBone.py
bones/textBone.py
customdatabases.py
skeleton.py

This should restore basic fulltext search capability in ViUR.
(Backported from a fixed project, should probably be tested separately before merging)

Restored fulltext search functionality

---

render/html/user.py

This issue was already fixed in ViUR 2.4 (issue https://github.com/viur-framework/server/issues/48) using pull request https://github.com/viur-framework/server/pull/159.
The changes in modules/user.py are correct.

Fixing error 500 in /user/login call, again

---

tasks.py

This keeps the current behaviour of task-overrides and includes some additional fixes

Futher fixes for Deferred Tasks. Replacement for #35

---

bones/relationalBone.py
bones/textBone.py
db.py
render/html/default.py
render/json/default.py
skeleton.py
tasks.py

Reenabled nomissing=1 parameter for add/edit
Mirror only bones listed in refKeys into our relation
Resolved several fixmes in renders
Improved Query-Debugging
Don't force the query to viur-relations if we sort by a relational property that is not multiple
Reimplemented getReferencedBlobs for relationalBone
Preserve \n in textBone
Removed obsolte and unused textExtension function from json-render

Whole set of resolved bugs/pending fixme's

---

tasks.py

fixed some problems with tasks and improved some loggings

---

cache.py

fixed request/site caching

---

render/json/default.py
skeleton.py
tasks.py

This simply fixes `_tasks/list`, but not well.
We just fake the skeleton system here and ignore it in the renderer... both bad solutions.
Any further suggestions on it?

Fixing _tasks/list

---

db.py

Fixed db.Query.clone()

---

skeleton.py

Fix cloning skeleton-instances with data

---

bones/relationalBone.py

The key proxy function does not seems to be a valid argument for the isinstance test

TypeError: isinstance() arg 2 must be a type or tuple of types

---

bones/userBone.py

Fixing performMagic on userBone

---

db.py

Like SQL, this will only return a subset of entries with each entry returned having at least
one different value in any of the fields listed in distinctOn than the other entries

Implemented distinctOn for Database queries.

---

bones/bone.py
bones/relationalBone.py
skeleton.py

- Moved embeded relSkelFromKey function from setBoneValue to top-level in relationalBone
- Pass the boneInstance and SkelInstance along to the defaultValue callable
Replacement for #94

Simpified creation of defaultValues for relationalBones

---

bones/relationalBone.py

setBoneValue with Not multiple relation with usingSkel fails

setBoneValue with Not multiple relation with usingSkel fails

---

bones/relationalBone.py

This commit adds the rel-part to the new createRelSkelFromKey introduced by #97, directly returning the {"dest"..., "rel"...} dictionary. This makes the function easier to handle and more transparent to the app that uses the function.

Improving new createRelSkelFromKey function to return a dict

---

render/xml/__init__.py
render/xml/default.py

Adapted XML-Render to new skeleton system

---

session.py

- No more support for cookies over unencrypted http
- Made the cookie SessionOnly (no max-age or expire time set) by default (it will vanish when the browser is closed)

Made the session-module TLS-Only 

---

bones/keyBone.py

Allow keybones to be multiple if they are not named "key"

---

tasks.py

Fixed serializing the currentUser for access in deferred tasks

---

render/html/default.py
skeleton.py
utils.py

Derive the currentPath from the path of the current file instead of os.getCWD

---

render/html/env/viur.py

... and some loggings with the old function name fixed as well.

Fixes getSkel to work with Singleton again

---

bones/__init__.py
bones/bone.py
render/json/default.py

This allows to set min/max length of a multiple bone and whenever duplicates are allowed.
This will currently only work with string/numericBones, for relations we'd have to decide what counts as duplicate.
This should resolve #79 and #115

First draft of a multiple constraint

---

prototypes/tree.py

query.Get() is now query.getEntry()

query.Get() is now query.getEntry()

---

bones/recordBone.py
prototypes/tree.py

had to remove a fix for recordBone that I already submitted in a separate PR

fixed a few bugs in tree.py code, passing key obj instead of strings etc

---

render/html/default.py

Just handle nomissing param in edit() as in add()...

handling nomissing param in edit as in add

---

bones/numericBone.py
bones/relationalBone.py
bones/stringBone.py
bones/textBone.py
i18n.py
render/html/default.py

Move LanguageWrapper to i18n; remove unused references to it; wrap return values from html render in LanguageWrapper

Fixes for i18n / multilanguage support

---

modules/user.py

* using utc based datetime objects to compare
* and made userpassword recovery great again!

Fixing UserPassword.recover draft

---

skeleton.py

With this changes we have an example-implementation for the QueryIter class as requested by @phorward in #108

Implement RebuildSearchIndexTask with QueryIter and remove not-implemented compact-mode

---

bones/textBone.py

This is the alternative PR to https://github.com/viur-framework/viur-core/pull/153

textBones are no longer indexed by default

---

modules/file.py

Fixed injectDownloadURL in file skel

---

tasks.py

This allows to iterator over a infinite amount of entries (you get a callback for each entry matched)

Implemented the QueryIter class.

---

render/vi/__init__.py

the current version does not work. This is a copy from the admin renderer.

Bug fixing for the getStructure function of the vi renderer

---

bones/numericBone.py

Fixed .replace() being called on non-string values in numericBone:isEmpty

---

template/editform_bone_select.html

Now we can again see the defaultValue of
boneParams in rendered html select options selected.
Disclaimer: not tested yet the multiple code path...

respecting defaultValue setting of selectBone in renderEditForm template

---

i18n.py
tasks.py

was still a currentRequest attribute. And reformat some lines.

Fix currentLanguage in i18n and tasks

---

skeleton.py

Prevent add/delete etc being called on a skeleton if an outputrender is attached

---

__init__.py
dbtransfer.py
modules/user.py
tasks.py

It now resides in email instead of utils

Fixed imports of the sendEmailToAdmins function

---

cache.py
db.py
prototypes/list.py
prototypes/singleton.py
prototypes/tree.py
request.py
skeleton.py

With these additions, the core will automatically track which queries/entities have been accessed inside a function decorated with @enableCache and flush the cache accordingly. Fixes #164

Ported cache tracking feature from server

---

bones/bone.py

Initialize the default-value to a list if defaultValue is None and the bone is multiple

---

bones/__init__.py
bones/bone.py
bones/codeBone.py
bones/rawValueBone.py

The codebone is a typed basebone for easier access in the frontend

Add rawValueBone

---

core/bones/fileBone.py

Weak fileentries have been deleted in certain versions of ViUR2 and only the relation has been kept.
With ViUR, we'll need that fileentry to be able to derive thumbnails etc.

Recreate the weak file entries on import from ViUR2

---

core/__init__.py

Fixed choosing another default (=top-level) render aside from html

---

docs/doc_tutorial/basic/viur_on_windows.rst

"How to" for running Viur3 on Windows

added Viur3 for Windows Documentation

---

docs/Pipfile.lock

updated pipenv lock file

---

core/bones/selectCountryBone.py

Additionally this commit removes the deprecated leading utf8-coding-line
and replace broad exception clause

Correct the naming of the ISO2->ISO3 country maps in selectCountryBone

---

core/bones/recordBone.py
core/render/html/default.py
core/render/html/env/viur.py
core/template/editform_bone_bone.html
core/template/editform_bone_bool.html
core/template/editform_bone_color.html
core/template/editform_bone_numeric.html
core/template/editform_bone_password.html
core/template/editform_bone_record.html
core/template/editform_bone_select.html
core/template/editform_bone_str.html
core/template/editform_bone_text.html
core/template/editform_row.html

This is the third attempt to enable recordBones(multiple=False) again in ViUR3.
It replaces #271.
Please see my comments below.

recordBone(multiple=False) - 3rd attempt

---

core/render/html/default.py
core/render/html/env/viur.py
core/render/html/user.py

Deprecate collectSkelData and removed it's usage

---

CHANGELOG.md
core/skeleton.py

Also added documentation for this function.
Fixes #290

Reenable the changelist evaluation in updateRelations

---

CHANGELOG.md
core/config.py
core/modules/user.py
core/resources/js/vi_user_google_login.js
core/template/vi_user_google_login.html

Migrated login with google to Identity Service

---

core/request.py

Disolved the redirect method in request.py

---

core/skeleton.py

This breaks output of skeletons in HTML

Don't use repr() as fallback for string

---

core/cache.py
core/db.py
requirements.txt

Fixed caching module, updated viur-datastore to 1.1

---

requirements.txt

Just a minor version bump of viur-datastore with updated changelog and readme - no code was changed ...

Feature/viur datastore bump to 1.2.1

---

core/bones/booleanBone.py
core/bones/dateBone.py
core/bones/numericBone.py
core/bones/stringBone.py
core/bones/textBone.py

I think we "generaged" enough of these widgets since VIUR 1.0 now...

Removing any generageSearchWidget functions

---

core/modules/file.py

This function is intended to be used by server-side code to write a file from any bytes-like object or buffer.

File.write() to write file from buffer

---

core/bones/relationalBone.py

This is the replacement for #383 based on current main branch.

Set format string back to established notation

---

core/bones/relationalBone.py

Replacement for #441, fix of #437.

Hotfix for invalid import of ReadFromClientError

---

core/bones/relationalBone.py
core/cache.py
core/dbtransfer.py
core/indexes.py
core/session.py

Remove keysOnly argument from some queries (related to https://github.com/viur-framework/viur-datastore/pull/6) and remove unused cursor (like in #438)

Remove keysOnly argument and unused cursor

---

core/bones/__init__.py
core/bones/sortindex.py
core/prototypes/tree.py

The SortIndexBone is a pre-defined NumericBone with a precision of 8, max value of pow(2, 30) and a defaultValue of the current timestamp.

Providing a SortIndexBone

---

core/session.py

This Pull Request fix an error in the PeriodicTask startClearSessions

Remove Parameter in doClearSessions

---

core/skeleton.py

- introduces new `substring_matching`-parameter to configure if substring matching should be enabled or not (default is True)
- introduces new `max_length` parameter to define the maximum tag length to be integrated into the search (defaults to 99, which is the previous hard-coded default)
- renamed `minLength` into `min_length` in hope this doesn't affect any working instances, and if so changes are minimal, to become more PEP8-compliant with the rest
- cleaned up some stuff and renamed some local variables to become more PEP8-compliant

Customizable ViurTagsSearchAdapter

---

CHANGELOG.md
requirements.txt

version bumped viur-datastore to 1.3.2

---

core/bones/string.py
core/render/html/default.py
core/render/json/default.py
core/render/xml/default.py

This pull request add a "maxLength" field for the stringBone. 
Also it changes some fields in the renderBoneStructure function for the string and textBone

Add maxLength for stringBone 

---

core/bones/text.py

so it allows multiple=True data to be saved

fixed getReferencedBlobs of TextBone

---

core/bones/base.py

This pull request adds an index  and a language in the fieldpaths values.
Like so
```{
"severity": 3,
"fieldPath": [
"stringtest4",
"en",
"0"
],
"errorMessage": "Zu Lang",
"invalidatedFields": null
}

Better fieldPath

---

core/tasks.py

Get now the project zone from the google metadata server.
https://cloud.google.com/appengine/docs/standard/python3/runtime#metadata_server

Get project zone from metadata.google.internal

---

core/bones/relational.py
core/skeleton.py

This PR replace the updateLevel  from int to an enum for better code readability. 
Also a DeprecationWarning is provided.

Add `RelationalUpdateLevel` (`Enum`)

---

.pep8speaks.yml

Wrote an .pep8speaks.ylm for the github action https://github.com/OrkoHunter/pep8speaks.
This will allow us to get comments of the pep8 conformance of our future pull requests

Add configuration for pep8speaks to enforce PEP-8-compliant pull request 

---

.github/workflows/pep8.yaml

@sveneberth and i added a Github action, which test for propper pep8 usage

Add workflow of GitHub-Action for linting

---

core/utils.py

Improve `utils.sanitizeFileName` to quote non-ASCII

---

core/request.py
core/tasks.py

This pr solve the issue #550 and add a (is_deferred) flag to the currentRequest Object

Add is_deferred flag to currentRequest

---

core/render/html/default.py
core/render/json/default.py

This pr add the indexed field to the boneStructure. It can be used in the VI or other frontend apps to filter the data better.

Add indexed in BoneStructure

---

core/config.py
core/modules/moduleconf.py

Hi there, this is a small refactoring of the new ModuleConf-module with the following changes:
- Standardized skeleton definition
- Provided adminInfo with a default "hidden" display
- Replaced f-strings that contained only one variable
- Replaced getattr-calls by default attr retrieval

Refactoring ModuleConf

---

core/modules/user.py
core/render/__init__.py
core/render/html/default.py
core/request.py
core/skeleton.py

* Substitute `projectBasePath` correctly with `viur.instance.project_base_path`
* Cast `Path` to `str` before `.replace()`
* Make use of the new Path and use context managers for I/O

Change usages of new path configs

---

core/bones/__init__.py

RelationalUpdateLevel should be in `from viur.core.bones import *`

Export RelationalUpdateLevel with viur.core.bones

---

core/skeleton.py

- PEP-8 encoding
- Updated __reserved_keywords list to further function names
- Replaced check on dot by check on valid characters from a given character pool

Improving MetaBaseSkel.fill_bonemap_recursive

---

core/render/vi/__init__.py

This fixes some problems with render.vi.getStructure, eliminates unused cases and handles an edge-case with a current project in relation to the Tree-prototype (the previous version generated invalid results).
Still, it is generally not a good solution, therefore an entire rewrite of this stuff becomes necessary soon.

Refactoring render.vi.getStructure

---

core/skeleton.py

This renames the encapsulated function fill_bonemap_recursive into MetaBaseSkel.generate_bonemap and makes it available for externals. This is required by a current project, which modifies skeletons at runtime.

Make MetaBaseSkel.generate_bonemap available

---

core/modules/user.py

This PR adds `admin_config` to the UserSkel to store configrations. In the new VI we want to store infos about the favorite modules of a user and now we can store it in a `JsonBone`

Add JsonBone for the user to store config information.

---

core/securitykey.py

This is a refactoring of the entire module without functional changes.

Refactoring `securitykey` module

---

core/bones/numeric.py

Add structure for NumericBone

---

core/__init__.py
core/config.py
core/modules/script.py

viur-scriptor is being integrated into the viur-core as a standard component. This commit implements the script-module and was initially created in a private repository.
This feature is mandatory for viur-core==3.4!

Implement `script` system-module for Scriptor tree

---

core/modules/user.py

This should become standard to allow for better pre-defined personalization.

feat: UserSkel improvements (`firstname`, `lastname`, `sync`) and Google Auth user information synchronization

---

core/prototypes/list.py
core/prototypes/singleton.py
core/prototypes/tree.py

feat: Add `manage` access right

---

core/modules/file.py

continue thumbnailing if a image is broken

fix: continue thumbnailing when image is broken

---

core/modules/user.py

This is a major hotfix, as user logins via Google or other, custom login handlers where able to authenticate users which are disabled by the system.

security: Ensure active status in authenticateUser

---

CHANGELOG.md
core/config.py
core/render/vi/__init__.py
core/version.py

This fixes the currently always succeeding version checking in viur-vi. This was NOT intended!

fix: Improvements and clarifications on version string

---

core/bones/base.py
core/bones/boolean.py
core/bones/numeric.py
core/bones/spatial.py

chore: Rename all `rawValue`-parameters to just `value`

---

core/render/vi/__init__.py

Fix /vi/config endpoint for complex data structure serialization

fix: enable to serialize complex custom config structures

---

core/render/html/default.py

This is an alternative PR to https://github.com/viur-framework/viur-core/pull/742

feat: Set `cls` to `CustomJsonEncoder` in Jinja's `json.dumps_kwargs`

---

core/bones/credential.py

Hello, it seems that we missed this PR which was proposed to be part of viur-core==3.4, so I've cherry-picked it now into main.

fix: `CredentialBone` without escaping (#702) - readded to main

---

core/bones/base.py
core/modules/file.py

...instead of AssertionError. Also includes some refactoring of the code here.
Proposal to resolve #727.

fix: `File.getUploadURL` with HttpExceptions

---

core/config.py
core/render/json/default.py

Introduces `conf["viur.compatibility"]["json.bone.structure.inlists"]` compatiblity flag, which can be removed.

perf: Avoid structure rendering in JSON render list

---

docs/Makefile
docs/Pipfile.lock
docs/conf.py

The [last build](https://readthedocs.org/projects/viur-core/builds/21561968/) failed

Fix docs configuration after #804

---

requirements.txt

chore: Update viur-datastore to 1.3.11

---

src/viur/core/email.py

feat: Implement a `PeriodicTask` to check the remaining SIB email quota

---

src/viur/core/modules/user.py
src/viur/core/render/html/user.py
src/viur/core/render/json/user.py

Hey @ArneGudermann, I still have several suggestion. I think it's easier to do this in this PR as batch.
This relates to #578

Improve authenticator otp

---

src/viur/core/modules/user.py
src/viur/core/securitykey.py

This is a follow-up pull request on #682 using the securitykey module to replace the viur-recovery attempt.

follow-up: Proposal for a recover process using extended securitykey

---

src/viur/core/render/html/env/viur.py

Import for https://github.com/viur-framework/viur-core/blob/a4f866df33a2c466683ba3a5ed78ab9305700bde/src/viur/core/render/html/env/viur.py#L90

fix:Add missing import

---

src/viur/core/modules/user.py
src/viur/core/prototypes/singleton.py
src/viur/core/prototypes/tree.py

This PR cleans up code from #800

refactor: Some clean-up on #800

---

src/viur/core/modules/user.py
src/viur/core/render/html/user.py
src/viur/core/render/json/user.py

feat: authenticator otp followup

---

src/viur/core/bones/boolean.py
src/viur/core/modules/user.py
src/viur/core/prototypes/list.py
src/viur/core/prototypes/singleton.py
src/viur/core/prototypes/tree.py
src/viur/core/request.py
src/viur/core/tasks.py
src/viur/core/utils.py

Redo https://github.com/phorward/viur-core/pull/5

feat: Implement `utils.parse_bool`

---

src/viur/core/modules/user.py

Improve second factors

---

src/viur/core/request.py

This PR adds missing `self` for #842

fix: _route list parsing for multiple bones

---

src/viur/core/module.py
src/viur/core/modules/file.py
src/viur/core/modules/page.py
src/viur/core/modules/user.py

- Fixes icons according to #851 (fixes #851)
- Fixes a typo in readonlyIf of UserSkel
- Updates documentation
- Updates modules and adminInfos using icons

fix: Updating admin info stuff

---

CHANGELOG.md
setup.cfg
src/viur/core/version.py

fix: Re-include `templates/` folder as data-files

---

src/viur/core/render/html/default.py
src/viur/core/render/html/env/viur.py
src/viur/core/request.py

Otherwise the default skey checks failing too.

fix: Remove the `style` which is reserved for template completely from the request kwargs

---

src/viur/core/modules/user.py

Fix for https://github.com/viur-framework/viur-core/pull/878/

fix: TimebaseOTP rename possible_user to user

---

src/viur/core/utils.py

This function is required for developments coming soon.

feat: `utils.is_prefix`-function

---

src/viur/core/render/vi/user.py

This PR add a check for a contextvar for the new admi and sends back only json.

feat: Add user admin login context

---

src/viur/core/modules/user.py

This works together with viur-admin >= 4.0.14.

fix: User-module default customAction triggers require skey

---

src/viur/core/bones/string.py

Resolve: https://github.com/viur-framework/viur-core/issues/932

feat: Add `min_length` to `StringBone`

---

src/viur/core/bones/select.py

fix: `defaultValue` type hint in `SelectBone`

---

src/viur/core/bones/text.py
src/viur/core/skeleton.py
src/viur/core/utils.py

refactor: Replace the `replace` function with `translate`

---

src/viur/core/cache.py
src/viur/core/email.py
src/viur/core/session.py
src/viur/core/skeleton.py

Otherwise this can lead to problems like https://github.com/viur-framework/viur-datastore/issues/43

fix: `exclude_from_indexes` has to be a set

---

src/viur/core/render/vi/__init__.py

fix: Admin-tool specific settings

---

src/viur/core/modules/file.py

This PR add a read Method for the `File` module so you can easy read files  from the Cloudstore.

feat: Add `File.read()` method

---

src/viur/core/tasks.py

`QueryIter` missing the same condition as in #1003
Therefore I refactored this with a method

fix: support for tasks emulator

---

src/viur/core/tasks.py

fix: config regression after incorrect merge 537f0e2

---

src/viur/core/render/vi/__init__.py

@ArneGudermann with the other change in my [working_branch](https://github.com/sveneberth/viur-core/tree/working_branch) this seems to work good with the vi-admin

feat: Support for nested modules in `getStructure()`

---

src/viur/core/modules/user.py

This improves PR #1033 for viur-core 3.6

fix: Help and comments on `UserPassword.pwrecover`

---

src/viur/core/tasks.py
src/viur/core/utils/__init__.py

fix: Wrong f-strings introducted by #1025

---

src/viur/core/bones/numeric.py

A `NumericBone` can be 0 or 0.0 (depending on the precíssion), in the default `iter_bone_value` this value would be skipped because of the falsy check and `return None`.
This causes loss of 0 values during `skel.refresh()`.

fix: customize `iter_bone_value` for `NumericBone`

---

src/viur/core/modules/moduleconf.py

This PR adds a recursive walk through all the modules and collects them in `read_all_modules`.
for further information take a look at #995

feat: Collect modules recursivly in `read_all_modules`

---

src/viur/core/bones/relational.py

fix: f-string in `RelationalBone` introduced in #950

---

src/viur/core/modules/user.py

fix: patch_user_skel (fix for #983)

---

src/viur/core/bones/file.py
src/viur/core/bones/relational.py

Tested. Might collide with #1022.

refactor: `RelationalBone`s `refKeys` and `parentKeys` as set

---

CHANGELOG.md
src/viur/core/modules/moduleconf.py
src/viur/core/version.py

- Refactoring
- `listFilter` that falls back to any modules the current user is allowed to see
- `canEdit` which evaluates the `{module}-manage` access right
- Moved `read_all_modules` as staticmethod into ModuleConf

fix: Several improvements on `ModuleConf`

---

src/viur/core/modules/moduleconf.py

fix `read_all_modules` after  #1073 and #1037 and merge 2a2b76ec16

fix: `read_all_modules` after  #1073 and #1037 and merge 2a2b76ec16

---

src/viur/core/skeleton.py

Resolves #1047.
@sveneberth  I hope I have understood your issue correctly.  
This PR sets the value of the bones to `None`.

feat: Allow `None` in `skel setBoneValue`

---

src/viur/core/bones/json.py
src/viur/core/bones/relational.py
src/viur/core/tasks.py
src/viur/core/utils/__init__.py
src/viur/core/utils/json.py
tests/main.py
tests/test_utils.py

Proposal to fix #1064.
I'm still a little unhappy with this, as it bites with #1000, but after all it's a different use case. Maybe we can bring both together in some way.

feat: `utils.json` module / improving `JsonBone`

---

src/viur/core/modules/file.py

fix: file module typo `UnprocessableEntity`

---

src/viur/core/bones/base.py

If a RelationalBone is computed and `Compute.raw`  is `False`, the unserialize function is called recursively and the value is recalculated all the time. This parameter is to prevent this

fix: Add `_prevent_compute` for computed Bones

---

src/viur/core/prototypes/list.py
src/viur/core/prototypes/tree.py

These parts where introduced by #1036

fix: Replace deprecated `utils.getCurrentUser`

---

src/viur/core/bones/string.py

This PR fix the Problem that the vale was cut off befor we check the `max_length`

fix: Readd `Stringbone max_length` check

---

src/viur/core/tasks.py

refactor: Move special system arguments for `CallDeferred` in `make_deferred`'s signature

---

src/viur/core/config.py
src/viur/core/email.py
src/viur/core/modules/file.py
src/viur/core/ratelimit.py
src/viur/core/securitykey.py
src/viur/core/session.py
src/viur/core/tasks.py

I think this is more readable than the old one.

feat: Add `PeriodicTask` can handle `timedelta` as interval

---

src/viur/core/bones/base.py

feat: Add support for single value  and `__default__` for multi-lang bones

---

src/viur/core/bones/base.py

feat: Add `sorted` feature to `MultipleConstraints`

---

src/viur/core/bones/__init__.py
src/viur/core/bones/string.py

feat: Add charset  `v_func` for `StringBone` 

---

src/viur/core/modules/file.py

This PR add the CRC32C and MD5 hash to the File skel. 
Resolves: #1176

feat: Add checksums for files

---

src/viur/core/modules/file.py
src/viur/core/tasks.py

- startCleanupDeletedFiles causes warning in any project
- Clarified docstring for `PeriodicTask`-decorator

fix+doc: PeriodicTask

---

src/viur/core/modules/file.py

chore: Adding file deprecations

---

src/viur/core/render/html/env/viur.py

Fix: Remove urlencode

---

src/viur/core/skeleton.py

This is a one liner  - seems we have to refactor a method...

fix: refactor _tagsFromString to _tags_from_str

---

README.md
pyproject.toml
src/viur/core/__init__.py
src/viur/core/scripts/viur_migrate.py

chore: Merging of `migrate_config.py` and `viur-2to3.py` into `viur-migrate` tool

---

src/viur/core/skeleton.py

Relates to https://github.com/viur-framework/viur-toolkit/pull/25

refactor: `Skeleton.patch()`s `db.IsInTransaction`-mode

---

src/viur/core/bones/relational.py

just provide correct argument shape

provice key_rel_list as list of tuples and not only a list

---

src/viur/core/bones/relational.py

fix: Add default Param for createRelSkelFromKey

---

src/viur/core/modules/moduleconf.py
src/viur/core/modules/script.py
src/viur/core/modules/user.py

Fix for: https://github.com/viur-framework/viur-core/issues/1035 and Replacement for #1315

fix: Name `f"server.modules.user.accessright.{right}"` correctly

---

CHANGELOG.md
src/viur/core/prototypes/list.py
src/viur/core/prototypes/singleton.py
src/viur/core/prototypes/tree.py
src/viur/core/version.py

feat: `SkelModule.structure()` with actions and with access control

---

src/viur/core/i18n.py

Ensure key is a str for every usage
Also here:
https://github.com/viur-framework/viur-core/blob/ec2c09e29adaedd490a2b7032590c6a91be78a3e/src/viur/core/i18n.py#L185

fix: Revert changes from #1323

---

src/viur/core/skeleton.py

- Provides a way to parse data into readonly bones as well
- Default for `Skeleton.patch()`'ed skeletons is to also allow to write into readonly bones

feat: Provide `ignore`-parameter for `Skeleton.fromClient`

---

src/viur/core/bones/spatial.py

This fix the Problem when you Import a `SpatialBone` from another System you get the data as a list.

fix: Allow `list` in `SpatialBone` `setBoneValue`

---

src/viur/core/render/html/env/viur.py

This is a general refactoring and some issue fixing with ViURs ugly and ridden-through jinja functions `getSkel()` and `getList()`.
Fixes bug #1343

fix+refactor: html-render `getSkel()` and `getList()`

---

CHANGELOG.md
src/viur/core/bones/select.py
src/viur/core/version.py

fix: `SelectBone.singleValueFromClient` doesn't accept `Enum` (backport #1320)

---

src/viur/core/bones/base.py
src/viur/core/bones/boolean.py

Also added some log output to `BaseBone.setBoneValue()` for better debugging of complex data.

fix: `BooleanBone.setBoneValue` doesn't respect language

---

src/viur/core/bones/base.py

...helps to better find the problem!

fix: Provide bone name with assertion message

---

src/viur/core/modules/script.py

fix: Improve and standardize `Script` module `vfuncs`

---

src/viur/core/bones/relational.py
src/viur/core/skeleton.py

... and some more on `updateReleations`. This finally kicks this piece of junk to hell and replaces it by something working, beautiful and clear.

refactor: `RelationalBone.refresh()`

---

src/viur/core/decorators.py
src/viur/core/module.py
src/viur/core/modules/script.py

fix: Custom decorators do not work

---

src/viur/core/bones/file.py
src/viur/core/skeleton.py

perf: Add check to avoid redundant `ensueDerived` calls

---

src/viur/core/bones/numeric.py

fix: `NumericBone.singleValueUnserialize` can't handle `str`

---

src/viur/core/modules/file.py

We've a bunch of old links to old ViUR2 blostore files like `/file/download/{{blobstore.key}}`.
Because the `{{blobstore.key}}` has an other encoding than the ViUR3 blobkey the request ends in a 500 `binascii.Error: Incorrect padding`. That's not server's fault, but client's, so a 4** is correct.

fix: Better handling of invalid blob keys in `File.download()`

---

src/viur/core/modules/translation.py

- Always return a dict with the lang as key (simplifies code!)
- Let backward-compatible `get_public` respectis old `languages`-parameter

fix: Further `Translation.dump()` clean-up

---

src/viur/core/prototypes/skelmodule.py
src/viur/core/prototypes/tree.py

`adjust_kind` must be a boolean.

fix: Change adjust_kind to boolean

---

src/viur/core/db/transport.py

fix: Fix `access_log` for `db.delete`

---

src/viur/core/bones/relational.py

1. Set tuple_check return value form `False` to `True` 
2. Fix the check for the `multiple`-`using` case.

fix: `RelationalBone` `multiple`-`using` case.

---

src/viur/core/cache.py
src/viur/core/config.py
src/viur/core/db/cache.py
src/viur/core/db/config.py
src/viur/core/db/query.py
src/viur/core/db/transport.py

1. Move `db.conf` to `viur.core.config`
2. Add  `conf.db_create_access_log` to prevent creating a access-log
3. Create DBConfig for compatibility reasons

feat: Move `db.conf` to `viur.core.config`

---

src/viur/core/session.py

fix: Avoid sending doubled Set-Cookie header

---

src/viur/core/bones/base.py
src/viur/core/bones/uid.py
src/viur/core/render/json/default.py
src/viur/core/skeleton.py
src/viur/core/tasks.py

refactor: Rename `IsInTransaction` to `is_in_transaction`

---

src/viur/core/i18n.py
src/viur/core/skeleton/skeleton.py

from : https://github.com/viur-framework/viur-core/pull/1454

ref: Replace old db calls

---

src/viur/core/bones/file.py

from : https://github.com/viur-framework/viur-core/pull/1454

fix: `ensureDerived` imports

---

src/viur/core/cache.py
src/viur/core/config.py
src/viur/core/db/cache.py
src/viur/core/db/config.py
src/viur/core/db/query.py
src/viur/core/db/transport.py
src/viur/core/db/types.py

Resolves: https://github.com/viur-framework/viur-core/issues/1519

refactor: Add `Database` `ConfigType`

---

src/viur/core/__init__.py
src/viur/core/modules/history.py

- Makes the `History'-module optional again, same as `File`
- More hooks to change value processing of History entries
- Improvements of the JSON-serialization using skel.dimp()

fix: `History`-module improvements

---

src/viur/core/prototypes/tree.py

Refactoring.
A key cannot be moved into its child anymore.
Fixes #1540 + #1490.

fix+refactor: `Tree.move()`

---

src/viur/core/render/html/default.py
src/viur/core/skeleton.py
src/viur/core/utils/__init__.py

_refSkelCache can have renderPreparation too.

fix: Remove renderPreparation of nested skeletons

---

src/viur/core/modules/user.py
src/viur/core/render/html/default.py

- Fixes the password recovery process via `UserPassword.pwrecover`
- Fixes HTML renderer's render.render to accept `None` skels
- Cleans-up some unused template variables

fix: ActionSkel paradigm for `user.UserPassword.pwrecover`

---

src/viur/core/module.py

fix: catch errors for annotated int or float arguments and reraise chained NotAcceptable

---

src/viur/core/render/html/env/debug.py

fix: Import `pprint` as `pp`
