viur-framework/viur-core

ratelimit.py

I fixed the probably typo which led to use the interface identifier, and not the network identifier.
This is already correctly in [l.57](https://github.com/sveneberth/viur-core/blob/eae5cb96a9e91357d2e804d676ecf9c994b3fcde/ratelimit.py#L57)

ratelimit.py - determinate IP:  Use the network identifier, and not the interface. 

---

skeleton.py

- Sometimes it's nice to simple access the stored values in a Skeleton, therefor I implemented the `getValues` method.
- I also implemented the `__iter__` with the usually python behavior to yield the keys.
- Finally I added some type annotations

SkeletonInstance.__iter__() and SkeletonInstance.__getValues__() incl. type annotations

---

render/html/env/debug.py

Without these args it wasn't possible to use a format logging string like this:
```jinja2
{% do logging("Hello %s!", "debug", "World") %}
```

added args to html-render logging function to support formatstring

---

request.py
tasks.py

This will fix deferred tasks called inside transactions on the local development server
as they would be called inside the transaction instead.

Deferr tasks to the end of the current request instead of calling them inline

---

bones/bone.py
modules/user.py

This allows the use of unique on properties that are not allways set (like uid in userSkel).
Currently, there can only be one user account that does not use oauth to authenicate as it locked the empty string

Added a lockEmpty property to UniqueValue

---

prototypes/list.py

Also renamed queryObj to just query (it looks nicer ;-))

Hotfixing query.get() which is now query.getEntry()

---

tasks.py

[Here](https://github.com/viur-framework/viur-core/blob/70a6f3fbece537ad522d7c554354769df1c4d1b2/tasks.py#L98) We would skip methods with an leading underscore from periodic execution, but never get an error. I added an Exception in the according decorator.

added exception for periodic decorated methods with leading underscore

---

skeleton.py

this fix adds a missing * to the chain parameter and casts the iterator to list. the doesMatch lambda function had a wrong parameter in its any statement
two possibilities either we cannot use an iterator here or it must be done differently

Subskel fix

---

session.py

This is a proposal to let ViUR/core save unique session cookies.
During testing, I recognized that I'm unable do a separate login in two instances running on the same machine, but different ports. This fix makes each session unique to the project id.

Make unique session cookies

---

render/html/env/viur.py

We do not check if we operate on unicode strings. urlencode automatically handles this for us in python3.x

removed unneeded and errronous if branch in updateURL

---

db.py

This caused filters added after a relational query rewrite to be applied directly to viur-relations (without src. or dest. prefix)

Fixed db.filterHook having only partial effect

---

skeleton.py

- the subskel named "*" was always integrated in the past
- it was possible to create subskels without the "key" bone
- IMHO "creationdate" and "changedate" should also be taken always

Fixing subSkel behavior to be ViUR2 compliant

---

bones/relationalBone.py

Currently, all relations that have a relSkel and are not multiple lose their data. 
This hotfix enables you to work with a single relation and relSkel.

subfield must always be parsed if a relSkel is defined even if it is not multiple

---

render/json/default.py

This error occurred when skellist is None, which occurs on a previous error.
Here's a log dump of a case where the problem occurred:
```
DEBUG    2020-07-21 14:49:57,575 request.py:391] Calling <bound method List.list of <modules.chatroom.ChatRoom object at 0x7f7d72415850>> with args=[] and kwargs={}
WARNING  2020-07-21 14:49:57,594 relationalBone.py:473] Invalid filtering! kind is not in parentKeys of RelationalBone users!
ERROR    2020-07-21 14:49:57,594 db.py:305] 
File "~/myProject/deploy/viur/core/db.py", line 300, in mergeExternalFilter
bone.buildDBFilter(key, skel, self, filters)
File "~/myProject/deploy/viur/core/bones/relationalBone.py", line 500, in buildDBFilter
name, skel, dbFilter, rawFilter = self._rewriteQuery(name, skel, dbFilter, …
```

Fixing AttributeError in json-renderer

---

config.py
render/html/env/viur.py

Load the SVGs as normal image.
And then replace them with the SVG itself:
```js
$('img.js-svg').each(function () {
var $replacer = $(this);
$.get($replacer.attr('src'), function (data) {
var $content = $(data).find('svg');
for (var i = 0; i < $replacer[0].classList.length; i++) {
$content[0].classList.add($replacer[0].classList[i]);
}
$replacer.replaceWith($content);
});
});
```

emebedSvg will now return an <img/>-tag in jinja renderer instead of the svg

---

modules/user.py

This will break some existing projects (mainly those who override getCurrentUser). We'll need to determine when to apply this one.

Made getCurrentUser return a userSkel instead of some properties copied from its dbEntry

---

skeleton.py

This PR fixes these two errors:
1. This occured when deleting entries:
```
INFO     2020-08-13 01:38:28,865 request.py:297] Running task directly after request: <function callDeferred.<locals>.mkDefered.<locals>.<lambda> at 0x7fc9b70531f0>
[2020-08-13 01:38:28 +0200] [22295] [ERROR] Error handling request /vi/_tasks/execute/clearKind?_unused_time_stamp=1597275500.0140002
File "/tmp/tmpE5EVA7/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 271, in handle
keepalive = self.handle_request(req, conn)
File "/tmp/tmpE5EVA7/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 320, in handle_request
respiter = self.wsgi(environ, resp.start_response)
INFO     2020-08-12 23:38:28,867 module.py:865] default: "POST …
```

Fixing two 500 errors relating key encoding

---

render/html/default.py

As decided in the viur-round at 2020-07-24 I unified the notation of relations in the html renderer. Unpack them always as dict with "rel" and "dest" like the json render.

Change notation for relationBone in renderBoneValue of html render

---

bones/recordBone.py

Same as in relationalBone, when working with existing viur2 datastore entries we will need this. Don't know if it has already been provided by someone else in some other branch though...

added backwards compatibility to recordBone singleValueUnserialize method

---

bones/bone.py

They have their own representation of "empty": an empty list
Further, this causes issues with relationalBones as an empty relationalBone's value would be [None] if we continue to add these

Don't add empty values to bones that are multiple

---

bones/dateBone.py

I recognized this bug within dateBone configured with time only on a ViUR 3 Project:
It has Following Traceback
```
-Traceback (most recent call last):
File "/mnt/c/users/unich/PycharmProjects/****/deploy/viur/core/request.py", line 218, in processRequest
self.findAndCall(path)
File "/mnt/c/users/unich/PycharmProjects/****/deploy/viur/core/request.py", line 392, in findAndCall
res = caller(*self.args, **self.kwargs)
File "/mnt/c/users/unich/PycharmProjects/****/deploy/viur/core/prototypes/list.py", line 218, in edit
skel.toDB()  # write it!
File "/mnt/c/users/unich/PycharmProjects/****/deploy/skeletons/termin.py", line 60, in toDB
return super().toDB(skelValues,clearUpdateTag)
File "/mnt/c/users/unich/PycharmProjects/****/deploy/viur/core/skeleton.py", line 858, in toDB
key, dbObj, skel, …
```

fixed dateBone(time = True, date = False)

---

render/html/env/viur.py

deriviation is a made up word, derivation was probably meant, but it means something different. derivate would be the correct noun. we should name variables correctly if we want international developers to understand what is going on

proposed var name correction in srcSetFor

---

bones/bone.py
bones/captchaBone.py
bones/colorBone.py
bones/credentialBone.py
bones/dateBone.py
bones/numericBone.py
bones/passwordBone.py
bones/relationalBone.py
bones/selectBone.py
bones/spatialBone.py
bones/stringBone.py
bones/textBone.py
modules/user.py
render/admin/__init__.py
render/json/default.py
skeleton.py

This moved "fieldPath of bones/bone.py:ReadFromClientError to 3rd place and made it optional.
Also, this field is now a list and will be automatically set (if used within a bone)

[Breaking] Fixed reporting of errors to Vi/Admin

---

bones/relationalBone.py
bones/spatialBone.py
bones/stringBone.py
db.py
modules/file.py
skeleton.py

This is needed for certain bones (spatial, random) as they run multiple queries in parallel, but each query needs to have a different sortorder. Consequently, we've also moved cursors and distinct into these new query objects.

Started to rewrite db.Query to support multiqueries with differnt sortorders again

---

bones/bone.py
bones/numericBone.py
bones/relationalBone.py
modules/file.py
modules/page.py

- Allow setting relationalBones (with multiple, and using) back to empty
- Fixed isEmpty handling in numericBone
- Fixed imports in modules/page

Set of parsing-fixes for new skeleton API

---

bones/fileBone.py
bones/relationalBone.py
modules/file.py
render/html/env/viur.py
tasks.py
utils.py

FileBones do now accept a validMimeTypes and maxFileSize parameter to restrict the files that are valid to assign
Up&Downloading now works without Serviceaccounts and with User-Credentials
Breaking changes:
- The parameter for "derive" in fileBones has changed. It's now a dict from the functionID to it's params
- getUploadURL in fileModule now requires clients to supply the fileName and mimeType in advance
The VI needs https://github.com/viur-framework/viur-vi/commit/c727fbf4ad3b62f1be173b495ad7475227a3a969 or similiar to be merged; the admin has support in the feature/py3 branch

Reworked file and derived handling

---

skeleton.py

Added the yieldBoneValues to SkeletonInstance.items() to allow iterating key-value pairs

---

render/admin/__init__.py
render/json/default.py
render/vi/__init__.py

This allows translations to be used anywhere (bone-descriptions; it's params; in values for selectBones etc).
Replaces #15

Made the json-render aware of our translation-class

---

prototypes/list.py

Raise NotFound as documented in https://github.com/viur-framework/viur-core/blob/21516d777cfd4c0784db8136ec3dd13c87fd4e41/prototypes/list.py#L189
Fixes #159

Raise NotFound if no entry was found in list-protypes edit

---

session.py

This is a fix for session values with >1500 bytes, which couldn't be stored.

Run fixUnindexableProperties on dbSession["data"]

---

modules/file.py
prototypes/tree.py
render/admin/__init__.py
render/vi/__init__.py

Using string here instead of the enum has several advantages, especially because it is checked and delegated in several situations from a string into the enum. This has been discussed in ViUR meeting from Mar 05, 2021.
With Python 3.8, [string literals](https://www.python.org/dev/peps/pep-0586/) will also be made available to test against in the annotations then.

Replaced enum Tree.TreeType by string

---

tasks.py

This changes allows to run tasks (with retries) in a separate request even on local development server.
I've used https://pypi.org/project/gcloud-tasks-emulator/
```sh
pip install gcloud-tasks-emulator
```
```sh
gcloud-tasks-emulator start -p=9999 -t=9090 --queue-yaml=deploy/queue.yaml --queue-yaml-project=$YOUR_PROJECT_NAME --queue-yaml-location=local -r 50
```
Take a look at `gcloud-tasks-emulator start -h` for the meaning of the commands
with the environment variable `TASKS_EMULATOR` pointing to the emulator-server.
```sh
dev_appserver.py -A $YOUR_PROJECT_NAME --port=9090 --env_var TASKS_EMULATOR=localhost:9999 deploy
```
(Alternatively you can add this in your app.yaml. However, be careful that you not deploy this, otherwise it will use this server in the cloud as well and will …

Add support to use a task queue emulator

---

core/__init__.py
core/config.py

This should prevent accidental deployments to the wrong application or starting the dev_appserver on another appid

Ensure the current projectid is whitelisted in conf["viur.validApplicationIDs"]

---

core/request.py

Currently, every type-error will return a NotAcceptable error to the client, even if it originates somewhere deep in the called function. This has now be limited to typeerrors according from a mismatch of parameters supplied and required from the called function (ie calling /view without a key)

Limit the scope of typeerrors which we raise NotAcceptable for

---

core/bones/passwordBone.py
core/render/html/default.py
core/render/json/default.py
core/render/xml/default.py

And prevent passwordBones from being rendered in html/json/xml render
As we don't escape passwords (to allow special characters) we must ensure it's never looped back to the client

Hash passwords in passwordBone early on (in fromClient)

---

core/bones/dateBone.py
core/render/json/default.py

Changed to always use timezone aware datetime objects, with UTC as default.
Fixed usage of localize flag.
Fixed documentation for singleValueFromClient.
Removed Workaround for a Python 2.7-only bug.
Removed datetimeToTimestamp, since it is never used. Additionally, it would convert local time into Unixtime, maintaining timezone time shifts. The posix timestamp should always be UTC-time, since no assumptions about timezone can be made.
Made pytz library mandatory.

Fix timezone mismatch in dateBone.py

---

core/modules/file.py

We now reinitialize the output BytesIO for each file (so the new thumbnail does not get appended to the previous file)
For thumbnails that are scaled to a specific width (instead of a excact resolution) the height is removed from the filename so it can be used without guessing the scaled height.

Fixed thumbnail deriver, changed output filename

---

core/email.py

This cannot have been tested on a live system. When passing a list of strings for bcc and/or cc, the core throws an uncaught exception because the keys are missing from the dataDict in the deliverEmail method. This fix is probably not elegant and may be improved by someone who knows what they are doing.

Fix for bcc and cc key error when trying to send an email

---

core/__init__.py

When all modules are derived from BasicApplication this a consistent pattern. To be backward compatible, the old style is still supported.
Old style for modules/index.py:
```py
class Index(object):
def __init__(self, *args, **kwargs):
self.render = default_render(self)
```
New style:
```py
class Index(BasicApplication):
pass
```
Additionally I simplify some parts, correct some ugly indentation/breaks, add type annotation and fix some docstrings.
This resolves #99 
Btw: Deferred and period-tasks works now quiet well in the index-module.

Add support to derive Index-module from BasicApplication

---

core/cache.py

"CURRENT_PROJECT_ID" does not exist anymore... just let the host OS report the env var "GAE_VERSION"

Determine appVersion in order for cache to work

---

core/modules/user.py

Instead of asking for the username, a new password and then sending out a link which will activate the new password,
we'll now ask for the username, send a key in the background if such a user exists, and then have a form bound to the session
that will ask for the recovery code and a new password.

Implemented a new password recovery process

---

core/skeleton.py

This causes the query to become a list of queries (due to the IN filter) - which currently don't support cursors.
We'll loose a minor optimization (we'll process more entities in updateRelations than we've to) so we should re-enable this as soon we support (internal) cursors on queries with a IN filter.

Temp. disable the changelist evaluation in updateRelations

---

core/tasks.py

This Bug has been ported from ViUR2 - it causes two deferred calls being executed in the same http request if the deferred function is not bound to a BasicApplication (eg. it's defined on module-level).

Fixed re-deferring in deferred calls

---

CHANGELOG.md
core/email.py

Currently, if f.E. None is contained in one list, only the deferred call will fail, making it hard to debug

Added validations to catch invalid recipient addresses early in sendEmail

---

CHANGELOG.md
core/config.py

Added connect-src: self and upgrade-insecure-requests CSP rules by default,
Replaced img-src  '*.ggpht.com' and '*.googleusercontent.com' (which where only used by the old blobstore) with storage.googleapis.com

Updated CSP-Rules

---

core/bones/recordBone.py
core/render/html/env/viur.py

- singleValueSerialize is called with None as value when the field is unset
- boneName may not be available the dictionary `skel["value"}` as key

Bugfixes for recordBone

---

CHANGELOG.md
core/skeleton.py

Serialize viurCurrentSeoKeys back to skel.dbEntity["viur"]["viurCurrentSeoKeys"]. As this bone is always read from this "viur" entity, we'd have also to write back to it, otherwise it's not usable in relations.

Fixed referencing viurCurrentSeoKeys in relations

---

CHANGELOG.md
core/bones/fileBone.py
core/modules/file.py

Some (very old projects) don't have their blobstore exposed in the cloud store yet, so these blobs have to be copied client-side.
The advance is that we don't have to resolve blob-store dlkeys to cloud-storage files, so we don't need a mapping service to be depoyed to the old project we're importing from.

Added logic to import blobs that have been copied client-side

---

CHANGELOG.md
core/render/html/env/viur.py

The old logic (deriving by groups) was broken anyway and this grands more finegraned control over which sizes we offer as not all sizes available may be useful in every context, added documentation

Made srcSetFor function in html render require a list of width or height

---

core/utils.py

This limits the potential damage if such a string gets embedded outside a parameter

Security: Also escape (, ), and = in escapeString

---

CHANGELOG.md
core/render/html/env/viur.py
core/utils.py

This will provide a consistent way for cache-busting resource links (eg /static/css/style.css?v={{getVersionHash()}}) when a new version is deployed

Added versionHash and appVersion to utils.py and html render

---

CHANGELOG.md
core/bones/selectBone.py

This is not needed in python3 as all dictionaries are sorted and will break if values are translated

Removed internal resorting of items in selectBone

---

core/request.py

Use the shorter `name` variable of the `HTTPException` instead of the verbose `descr`.
Then we also use the Reason-Phrases suggested in the [RFC 7231 Sec. 6.1](https://datatracker.ietf.org/doc/html/rfc7231#section-6.1).
Test with:
```py
class Index(BasicApplication):
@exposed
def testEx(self):
raise errors.NotFound()
```
and
```sh
curl -I http://localhost:8080/testEx
```
Old result:
```plain
HTTP/1.1 404 The requested resource could not be found.
...
```
New result:
```plain
HTTP/1.1 404 Not Found
...
```

Correct the response status code

---

core/request.py

This enables Ajax-requests to access detailed information when something went wrong. This is already implemented in flare, for example.

Set x-viur-error in header with exception description

---

core/skeleton.py

This bug raises when a skeleton was configured to use unique bones while data has previously been written.

Fix: Don't fail when bone_unqiueIndexValue is None

---

core/config.py
core/skeleton.py

Provide a viur.debug.skeleton.fromClient config flag to log debug, which is easier for development.

Log higher severity errors raises from bones

---

core/skeleton.py

This is also stated in the docstring before, but didn't work as subsequent calls access properties not implemented in dict.

Cure/rel skel.unserialize()

---

core/bones/bone.py

This...
```python
b = stringBone(multiple=True)
skel["b"] = "test"
```
...will write `['t', 'e', 's', 't']` into the bone in the datastore.
This fix will write `["test"]`, as wanted.

Raise exception when invalid objects are assigned to multiple=True bones

---

core/prototypes/tree.py

This change sets the readOnly-bones parentnode and parentrepo of a TreeSkel before the fromClient call. The reason for this is, that in a specific use-case, a unique value is build, which may only be unique per repository. This construction was made in a custom fromClient function implemented on the Skeleton, which requires the parentrepo to be known.

Set parentnode and parentrepo before fromClient()

---

core/bones/relationalBone.py

In case `rawFilter[name].lower() == "none"` and rawFilter[name] is something else than str, ViUR will crash here.

Fix buildDBFilter rawFilter condition

---

core/securitykey.py

This little improvement might help to fix issues when porting from ViUR2 to ViUR3.

Assert kwargs are empty on session security key

---

CHANGELOG.md
core/bones/bone.py
core/bones/stringBone.py

Moved the language type check to basebone and removed obsolete/dulicate/broken code for languages handling in stringBone

Fixed serializing stringBones with languages without prior fromClient call

---

core/bones/dateBone.py

a datetime object without a timezone is a naive datetime object, not a native one...

fix typo in error message

---

CHANGELOG.md
core/errors.py
core/request.py

This class is replaced by the new dataclass `bones.bone.ReadFromClienError`.
Furthermore this one should not be raised, because this doesn't inherit the `Exception` class, as written in the docstring.
Replace the last usage with `errors.BadRequest`.

Remove errors.ReadFromClientError

---

.gitignore
Pipfile

create a .pypirc file in root directory with secrets to publish on pypi and testpypi.
https://packaging.python.org/en/latest/specifications/pypirc/
Than you can use `pipenv run release` to publish on pypi and `pipenv run develop` to publish on testpypi

 switch from env vars to pypi config to allow develop releases on testpypi

---

core/bones/sortindex.py

basebone need 2 parameters, which are missing
`File ".../viur/core/bones/base.py", line 197, in getDefaultValue
return self.defaultValue(skeletonInstance, self)
TypeError: <lambda>() takes 0 positional arguments but 2 were given
`

fix: sortindexbone lambda function fix

---

core/bones/__init__.py
core/modules/file.py

Due the renaming of bones.stringBone into bones.string, the stdlib `import string` and then `from viur.core.bones import *` afterwards causes the assert with string.ascii_digits etc. to fail.
This fixes it entirely and cleans up Skeleton definition of the file module generally (formatting, index=True removal)

Fixing file module

---

CHANGELOG.md
core/skeleton.py
core/utils.py

- seoUrlForEntry might created a legacy_urlsafe_key if called from jinja which is not supported
- Checking for duplicate seokeys was broken
- Unsupported values (True and None) where erroneously included in activeSeoKeys

Fixed seoKey handling in skeletons and fixed seoURLtoEntry

---

core/securitykey.py

Remove "None" as parameter when calling `doClearSKeys`, because function changed here https://github.com/viur-framework/viur-core/commit/bb407494b385d25525e87e90dffa2b6e1becb4c9

Remove Parameter

---

core/errors.py
core/modules/user.py
core/ratelimit.py

Implement an exception class for HTTP Status "429 Too Many Requests"
and use it instead of Forbidden for rate limit blocked actions.

Implement `errors.TooManyRequests` exception

---

core/request.py

Parse also `Literal` type annotations in exposed methods.
Literals were introduced with [PEP-586](https://peps.python.org/pep-0586/) for Python >= 3.8.
Example:
```py
from typing import Literal
from viur.core import exposed
@exposed
def my_method(self, value: Literal['a', 'b', 7]):
...
```
Only `'a'`, `'b'` and `7` are allowed for `value`. Other values will be rejected.
The `7` will be accepted as `str`, but forwarded as `int`.

Add support for `Literal` type annotations in processTypeHint

---

core/tasks.py

This pull requests fixes the bug, that the formatstring `"d.%m.%Y %H:%M:%S"` is used for task value (de-)serialization inside of deferred tasks.
This is what happens when this broken format string is used:
```python
$ python
Python 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> d = datetime.datetime.now()
>>> s = d.strftime("d.%m.%Y %H:%M:%S")
>>> s
'd.08.2022 18:05:19'
>>> datetime.datetime.strptime(s, "d.%m.%Y %H:%M:%S")
datetime.datetime(2022, 8, 1, 18, 5, 19)
```
This fix will be turned into v3.2.1 as it is a serious issue.

Fixing invalid datetime (de)serialization for tasks

---

core/skeleton.py

This fix ensures that the full skel used to store all values inside toDB() is of the same skeleton class as mergeFrom.
The previously supposed idea was
```python
skel_cls = skeletonByKind(mergeFrom.kindName)
assert mergeFrom.skeletonCls is skel_cls
skel = skel_cls()
```
but this is the more elegant way, I think.

Get full skel instance by skeletonCls instead

---

core/bones/key.py

- Implemented singleValueFromClient to parse external values for KeyBones
- KeyBone accepts optional allowed_kinds parameter
- Reported two bugs to viur-datastore team for fixing

Improving KeyBone

---

core/render/html/default.py
core/render/json/default.py
core/render/xml/default.py

This pull request adds validMimeTypes to the BoneStructure. So that you can use them on the client side to select files.

Add valid mime types to the BoneStructure

---

core/bones/numeric.py
core/bones/sortindex.py

This pull request set the max value for a SortIndexBone higher, because the UNIX timestamp is lager than 2^30.

Set new max Value for SortIndexBone

---

core/i18n.py

This pull request solves the problem that the core crashes when you pass a key to the translate that is not of type string.
https://github.com/viur-framework/viur-core/blob/c89dfd68b595ffa9c2a0f0e09d0984bf18cd3bd8/core/modules/user.py#L64-L72
runs through
https://github.com/viur-framework/viur-core/blob/c89dfd68b595ffa9c2a0f0e09d0984bf18cd3bd8/core/render/json/default.py#L84-L87
or this:
`testSelect=SelectBone(descr="testSelect0",values={"a":1,"b":2,"c":3})`

Convert TranslationsKey

---

core/bones/key.py

Allows for defining `KeyBone(check=True)` which checks if the given key does exist. This should prevent from setting KeyBones to arbitrary keys.
This is a preliminary for Tree extensions planned.

Extending KeyBone to check given key's existence

---

core/bones/spatial.py
core/render/html/default.py
core/render/json/default.py
core/render/xml/default.py

Checks if boundsLat boundsLat are valid values.
See https://docs.mapbox.com/help/glossary/lat-lon/
Set boundsLat,boundsLat in the renderBoneStructure.

Improving SpatialBone bounds checking and use `float` instead of `int`

---

core/render/html/default.py
core/render/json/default.py
core/render/xml/default.py

- Redundant code refactored into single functions
- Added a consequent action-parameter to all functions
- in HTML-renderer, the action describes the concrete action that
is triggered, but the default name of the template is used from
the specific action.
- This means, e.g. a clone-operation uses edit and editSuccess, but will pass action=clone, so the template renders editTemplate and the template can decide whether it provides a different form for a clone-operation or not.
- Removed tree-specific functions as they are now solved as edit-actions
- This is a preliminary for further development on the tree module
This commit is fully backward-compatible to existing code.
Further improvements, modularization and removal of bad code will follow later.

Refactoring default renders for HTML/JSON/XML

---

core/bones/string.py

This can still be overridden individually using the `isEmptyFunc` parameter that can be given to a bone. Fixes #496.

Implement isEmpty-function for StringBone

---

core/__init__.py

Hello this pull request create a new hmac key if there is no one set and write to in the database.
Maybe we should delete this in the viur-base .
https://github.com/viur-framework/viur-base/blob/9cede043ceb286dca6e898115b83212623a0afec/deploy/main.py#L52

Create a new hmac Key if no one is set

---

core/bones/__init__.py

Since we renamed the bones and implemented `__all__` and this is dynamically generated, PyCharm is no longer able to recognize the definition. Since this is only a temporary solution and is the clean way anyway, I have added the bones with original names. So the reference works again in PyCharm.

Add bones to __all__

---

core/bones/file.py
core/cache.py
core/email.py
core/modules/file.py
core/modules/user.py
core/prototypes/tree.py
core/securitykey.py
core/session.py
core/skeleton.py
core/tasks.py
docs/doc_tutorial/basic/10_training_datamng.rst

- Cleans the @CallDeferred decorator's internals to behave equally with or without a task queue
- Added more debug to find bugs
- Renamed callDeferred to CallDeferred
- Added wrapper callDeferred with deprecation warning
- Further renamings of typo "defered" into "deferred" and PEP8-names for replaced items
- Reverted logger use back to logging, I will explain for this. We should make this later on.

Cleaning up and renaming CallDeferred

---

core/bones/relational.py
core/skeleton.py

- Use skel.refresh()
- Added logging for useful stuff (i.e. which entity is going to be refreshed)
- Removed logging for not so useful stuff

Use skel.refresh() in updateRelations

---

core/logging.py

...which caused redundant logging output on local dev app server.
Old output was:
```
DEBUG:root:foo bar
DEBUG    2022-09-30 18:24:38,445 example.py:49] foo bar
```
Now we only get the latter.

Remove default logging handler 

---

core/skeleton.py

- PEP8-compliant variable name
- Fixed typo that defined "limitstyle" as a reserved keyword, but not "limit" and "style"
- Added "bounce" which is used by add/edit
- Sorted alphabetically
- Fixed exception raise

Redefining __reserved_keywords

---

.github/workflows/publish.yml
.github/workflows/python-test.yaml
.readthedocs.yml
Pipfile
Pipfile.lock
docs/Pipfile
docs/Pipfile.lock
requirements.txt
setup.cfg
tests/Pipfile
tests/Pipfile.lock

This PR should enforce use of Python==3.10.
Afterwards, we can try to add Python 3.11 support as well.

Enforce python3.10

---

core/bones/relational.py

An enum datatype is not supported and causes an error.
Fixes #523.

Use `.value` of the RelationalUpdateLevel enum in a datastore entity

---

.readthedocs.yml

#525 increased the python version to 3.10 for read the docs, but the [latest supported version is 3.8][1]. Therefore the [builds failed][2] However, the configuration file v1 is deprecated anyway. So I upgraded to version 2 which supports 3.10.
So, the [build][3] was successful, again :smiley:.
[1]: https://docs.readthedocs.io/en/latest/config-file/v1.html#python-version
[2]: https://readthedocs.org/projects/viur-core/builds/18449541/
[3]: https://core.docs.viur.dev/en/change_read_the_docs_config/

Upgrade read the docs to v2

---

core/bones/boolean.py
core/config.py
core/request.py

VIUR currently allows only to pass True, yes or 1 as valid strings when a bool type hint is accepted. This is confusing, especially when true is provided, which is the valid true keyword for boolean true in the javascript word (and also many other, more professional programming languages than Python...)

Accept variations parameters with bool type hints

---

core/modules/user.py
core/prototypes/list.py
core/prototypes/singleton.py
core/prototypes/tree.py
core/tasks.py

If you make a POST request with valid form data but don't provide a skey, you get no error currently. Only if you provide invalid skey. Let's always raise an 412, no matter if the skey is missing or wrong.

Remove `skey == ""` check from add/edit methods.

---

.github/workflows/pep8.yaml

A pull request might contains multiple commits. Therefore we need to diff between the base and the head branch. But on pushes only the current commit should be diffed.
Resolves #553

Fix linter GitHub Action workflow

---

core/bones/relational.py

Fix bug in https://github.com/viur-framework/viur-core/blob/6b1182d9482dd962332983763cda81f761cf184f/core/bones/relational.py#L161
That the updateLevel can only be zero or one but it also can be two.
https://github.com/viur-framework/viur-core/blob/6b1182d9482dd962332983763cda81f761cf184f/core/bones/relational.py#L25-L29

relationalBone-updateLevel-Enum-fix

---

core/config.py
core/render/admin/__init__.py
core/render/vi/__init__.py
core/render/xml/__init__.py
core/utils.py

- Allows to perform deprecation behavior on config variables
- Implemented deprecation behavior for #552
- Remove unused config variables
- Fixed some deprecation warnings to become more clear (tested locally)
---
I'm assuming these defaults are unused, and propose a removal of them:
- `"viur.capabilities"` is used in renderer to provide some "additional" undocumented information about modules. Seems to be a relict of ViUR v1, never seen this in any recent project.
- `"viur.db.caching"` is not found in either viur-core or viur-datastore anymore
- The variable `apiVersion` was used NOWHERE.

Implement conf-dict as Conf-class

---

core/__init__.py

This PR should fix this https://github.com/viur-framework/viur-core/issues/571. it imports the standart logging module after the core logging module. It work for me now:

`import logging` must stay behind other imports in `__init__.py`

---

core/__init__.py

This PR fix the bug when the core is  imported as package and not as a submodule the index.yaml can't be found.

Change path of index.yaml in load_indexes_from_file

---

core/modules/user.py

- Cleaned imports
- Cleaned obsolete notations (super-calls, inherit from object)
- Renamed classes to be PEP-8 compliant
- Cleaned code-style
- Deprecation warning for `userSkel` use, rather than `UserSkel`

Code clean-up for core user module

---

core/modules/user.py

This PR added back the kindname for the userskel , because is can not be imported now when the Userskel is only defined in the core.
The problem is here we set the kindName here:
https://github.com/viur-framework/viur-core/blob/e6146a103599a2286f015332860b319968c5aac9/core/skeleton.py#L403-L409
but this `not relNewFileName.strip(os.path.sep).startswith("viur") ` is False. Because of this we must pre set the kindName.

added back kindName for userSkel

---

core/render/json/default.py

This is a hotfix that provides a defaultvalue in the JSON bone structure rendering. It fixes problems with hidden bones in using-skels of RecordBone and RelationalBone, as the values for these skeletons are created within the client without server feedback.
It works together with https://github.com/viur-framework/viur-vi/commit/2809cf6c06519b1cb3cd49abc3f75149b495b552 and https://github.com/viur-framework/flare/commit/1e07a3c22be0a8917dfa7e5ae2f8c9217a3d0b23.

Provide defaultvalue in bone structure

---

core/securityheaders.py

This PR fixes that the Content-Security-Policy header is always expanded when an error occurs.

Fix growing instance's Request header due continous change of global CSP rules

---

core/prototypes/tree.py

This is a hotfix, the wrong skeleton is used in two places.

Use editSkel() in Tree edit/delete

---

core/__init__.py

This fixes a deprecation warning introduced by #582 in the own sources, as this was forgotten to be replaced ;-)
This PR also adds a `# noinspection PyUnresolvedReferences` to an import in the same file for better readability.
Relates to #570 which can be closed afterwards as well.

Fixes a deprecation warning introduced by #582

---

core/render/html/default.py
core/skeleton.py

This PR reset the `renderPreparation` in `renderEmail` because if we use a Bone after we send an email we got an wrong type.
Example:
```python
skel = self.editSkel()
if not skel.fromDB(key):
raise errors.NotFound()
print(f"""before:{type(skel["key"])}""")
email.sendEMail(dests=["test@mail.com"], tpl="viur_mail_dummy", skel=skel, sender="test@mail.com")
print(f"""after:{type(skel["key"])}""")
```
We got : 
```
before:<class 'viur.datastore.types.Key'>
after:<class 'str'>
```

Reset renderPreparation in renderEmail

---

core/modules/user.py
core/session.py

This is a replacement for #615 and bases on the branch from @sveneberth.
It uses the baseSkel() of the user module more excessively and cleans-up the session field takeover.

Improvements for User module (substitutes #615)

---

core/bones/numeric.py
tests/bones/test_numeric_bone.py

This refresh method ensures numeric values in the datastore.
This might be helpful if you change a StringBone to a NumericBone. You can do a rebuild search index and the strings will be converted to numbers.
This behavior was done in ViUR2 on every unserialize: https://github.com/viur-framework/server/blob/e53c744834103a467a5f51b6b29db7aa531a6096/bones/numericBone.py#L83-L93
---
There's one logical change, because I think this is the most transparent way:
Before, `isEmpty()` determined `"42.0"` with precision as empty, because the `int("42.0")` cast raised a `ValueError`. Now we convert it first to float, then to int.
In case of `precision > 0` this value was already accepted.
---
I'm unsure about the behavior what `refresh` should do on _invalid_ data (a list, embedded entity, ...)
1. …

Implement a refresh method in the `NumericBone`

---

core/config.py
core/request.py

With this PR you can now set if you want to see your local log entries also in google cloud logger. I don't think it's necessary to send all your logs to google, because it costs time and memory unnecessarily. 
It also halves the response time in the local mode for simple requests.

Add `conf["viur.dev_server_cloud_logging"]`

---

core/session.py

This PR avoids that when a skey is validated the session is written twice to the database. 
First in the Transaction : 
https://github.com/viur-framework/viur-core/blob/50e493b9c1ef56937b77ff77286c876790e99d76/core/session.py#L226-L234
And second time at the end of the request if the session `changed` marker is `True`

Avoid that session is written twice when validating an skey

---

core/config.py
core/render/json/default.py
core/skeleton.py

- skel.structure() should always be a dict
- json.DefaultRender.__rewrite_structure() rewrites the structure according compatiblity flags from `conf["viur.compatibility"]`
- By disabling `json.bone.structure.keytuples` one gets a structure dict directly

Improvements for new skel.structure() feature (PR for #637)

---

core/tasks.py

* deferred tasks and `QueryIter`s are now running in the version in which they were called. (Resolves #641) This behaivor is equal as in the viur-server. But the version can be changed with the argument `_target_version`.
* Implement `_eta` and `_name`: These params were handled directly by the google api in the python2 runtime (https://cloud.google.com/appengine/docs/legacy/standard/python/refdocs/google.appengine.api.taskqueue.taskqueue#google.appengine.api.taskqueue.taskqueue.add) and were not ported.
* Remove `_retry_options`: This option does not longer exist as in the python2 runtime. We could set `retry` to `google.api_core.retry.Retry` (https://github.com/googleapis/python-api-core/blob/b8e75cff8bf6772ab76ca6f8d3c80dc2580075c7/google/api_core/retry.py#L222) but this expects a …

Improve Cloud Tasks creation in `CallDeferred` and `QueryIter`

---

core/prototypes/__init__.py

Using just `Module` will raise more incompatiblities (tested!)

Fallback to `SkelModule` as replacement for `BasicApplication`

---

core/bones/file.py
core/modules/user.py
core/skeleton.py

This PR finaly replace `clearUpdateTag` with `update_relations`. I think this is more understandable.

refactor: rename `Skeleton.toDB()`s `clearUpdateTag` into `update_relations`

---

core/request.py

Rework of #686
Create a json error message if we are in the json/vi renderer and have a normal Exception not a HttpException.

fix: Return JSON-encoded response for internal server errors too

---

core/securitykey.py
core/session.py

This PR replace `do_clear_skeys` and `doClearSessions` with a more elegant  way of `DeleteEntitiesIter.startIterOnQuery`

refactor: Replace `doClear*` by `DeleteEntitiesIter`

---

core/bones/text.py

ignore downloadUrls without signature

fix: ignore downloadUrls without signature

---

core/render/json/default.py

The reason for this relates to issue #649 and is an extension on #651, to avoid losing the bone order in case the specific client language does not implement object keys order, which is e.g. the case with JavaScript.

feat: Inject "sortindex" attribute to bone structure

---

core/bones/password.py
core/modules/user.py
core/utils.py

Since python 3.4 https://docs.python.org/3/library/hashlib.html#hashlib.pbkdf2_hmac is in the standard. This PR replaces the own implementation with this one.
Furthermore, for security relevant tokens not the [`random`](https://docs.python.org/3/library/random.html#module-random) module but [`secrets`](https://docs.python.org/3/library/secrets.html) should be used. Therefore there is now an extension of `utils.generateRandomString`.
> _Warning The pseudo-random generators of this module should not be used for security purposes. For security or cryptographic uses, see the [secrets](https://docs.python.org/3/library/secrets.html#module-secrets) module._
~ [Docs at python.org](https://docs.python.org/3/library/random.html#:~:text=Warning%20The%20pseudo%2Drandom%20generators%20of%20this%20modu …

refactor: Re-implement password encoding using Python's `hashlib` and `secrets` module

---

core/modules/file.py

Currently you can not rename a file in viur. If you change the filename the core can't find the file anymore because the name is only changed in the database not in the GCloud Storage. Now we move the file to the new name and delete the old file. Because GCloud Storage can't rename a file. 
(https://cloud.google.com/storage/docs/copying-renaming-moving-objects#move)

fix: Keep filename synchronous in both skeleton and blob

---

requirements.txt

This updates viur-datastore to 1.3.8 with some minor fixes and improvements.

chore: Bump viur-datastore to 1.3.8

---

core/skeleton.py

This is a hotfix on pull request https://github.com/viur-framework/viur-datastore/pull/19, it was forgotten to modify SkelList here as well.

fix: `SkelList.get_orders` must be in the `__slots__`

---

core/bones/date.py

Because the datastore (currently) enforces datetime aware objects we need to remove/add the tzinfo on (un)serialize.
This is a replacement for #642

feat: Implement naive mode in `DateBone`

---

core/render/json/default.py
core/skeleton.py

"sortindex" is injected differently, and becomes general part of the skeleton structure dict.
This is a hotfix on #651 and improvement on #698.

fix: Run render_structure recursively on "using" and "relskel"

---

CONTRIBUTING.md

Adding rules for conventional commits to CONTRIBUTING.md, and for the versioning scheme regarding pre-releases.
However, I have to make two personal comments here about Conventional Commits:
1. I really HATE the keyword "chore".
2. Why is it called "feat", and not "feature", but "refactor" and not "refact"? This is so ugly and stupid, it seems that Conventional Commits where invented by idiots... well, it has its origin in the JavaScript world, this might be the reason.

chore: Conventional commits and clarifications

---

core/bones/credential.py

This PR remove the string escaping in the credentialBone because it change the credetial value. 
An example we have an Base32 Secret like `GZRTOMBZREHFTDQNJVGQYRYMRSTOOLCGNSWKNQ==`
and we store it in the Bone. 
Later  we have want  compare the token in some OTP function or so and now we get `GZRTOMBZREHFTDQNJVGQYRYMRSTOOLCGNSWKNQ&#061;&#061;` from the Database.

fix: `CredentialBone` without escaping

---

docs/conf.py
docs/rtdtemplate/layout.html

Sphinx removed jQuery (https://github.com/sphinx-doc/sphinx/issues/9974), but our current theme requires it (otherwise the search and version selection doesn't work).
As quick & dirty solution I've added a jQuery import to our template. In the long term, we should bring our template up to date.

doc: Set language in readthedocs config and add jQuery

---

core/bones/select.py

Compare the value in case of `Enum`-values as string too. The data we get from client are strings, these aren't equal to ints (like in the user status) and wouldn't be valid for this bone.
Replaces #725

fix: comparision in `SelectBone.singleValueFromClient`

---

core/bones/select.py

Fixes the type annotation to allow for `str` as well. Otherwise, the defaultValue parameter is highlighted as invalid with a setting like `SelectBone(values={"a": "A", "b": "B"}, defaultValue="a")`.

fix: SelectBone `defaultValue` type annotation

---

core/skeleton.py

Rename the misspelled `__undefindedC__` into `__undefined__`.

chore: Rename `__undefindedC__` into `__undefined__`

---

core/bones/base.py

This renames the misspelled global `__systemIsIntitialized_`  into `__system_initialized_`.

chore: Rename `__systemIsIntitialized_` into `__system_initialized`

---

core/skeleton.py

The first line is always the subject.

fix: Remove leading `Subject: `  from task notify emails

---

core/skeleton.py

This is a fix for #731 you can't use `__` before a var because this indicates a private class  var in Python. 
You get an error like:
`NameError: name '_Skeleton___undefined' is not defined`
https://docs.python.org/3/tutorial/classes.html#private-variables

fix: Rename `Skeleton.__undefined` into `Skeleton._undefined`

---

core/request.py

Remove an `if`, otherwise the `else` case is missing and we have a path with `res = None`

---

core/request.py

This PR add  the `path_list` to th init function and move the path validation to the start of `findAndCall`
Problem:
If we make a call with to many arguments a `BadRequest` error is raised befor the path is processed. And than this :
https://github.com/viur-framework/viur-core/blob/d405faae32dfa503ef786fad32e3c7bb483f51d0/core/request.py#L312
crashed with.
`AttributeError: 'BrowseHandler' object has no attribute 'pathlist'`

fix: Add path_list to the __init__ of BrowseHandler

---

core/render/json/__init__.py
core/render/vi/__init__.py
core/request.py

Hello, this is both a feature containing a bugfix for the type annotation.
The feature is required for a current customer project. It is very restricted.
- Restricted possibility to generate a fresh, non-session skey with a duration between 1 and 60 seconds for authenticated users
- Fixing type hint parsing, which needs a general refactoring

feat/fix: Allow `duration` argument for skey

---

core/bones/date.py

Hi there,
I came across this error with a project I'm porting from version 3.3.5 to 3.4. The `DateBone.fromClient()` function is called with a ISO-string `2023-02-20T12:26:01+01:00` and fails, because the timezone is already provided. 
Furthermore, the case with `now` was not part of the localization done below. The behavior is now corrected, the bug was introduced by #667.

fix: `DateBone.fromClient()` should regard tzinfo

---

core/modules/user.py

This is a hotfix for a TypeError which happens in case the password is not set or the user does not exist.
```
[2023-05-15 17:22:22,914] /.../viur/core/request.py:299 [ERROR] ViUR has caught an unhandled exception!
[2023-05-15 17:22:22,914] /.../viur/core/request.py:300 [ERROR] a bytes-like object is required, not 'str'
File "/home/user/.local/share/virtualenvs/project-viur3/lib/python3.10/site-packages/viur/core/request.py", line 275, in processRequest
self.findAndCall(path)
File "/home/user/.local/share/virtualenvs/project-viur3/lib/python3.10/site-packages/viur/core/request.py", line 623, in findAndCall
res = caller(*newArgs, **newKwargs)
File "/home/user/.local/share/virtualenvs/project-viur3/lib/python3.10/site-packages/viur/core/modules/user.py", …
```

fix: Fixes TypeError when password is unset

---

core/bones/boolean.py

Otherwise the serialize fails with 
```
File "/.../lib/python3.10/site-packages/viur/core/bones/base.py", line 461, in serialize
if language in newVal:
TypeError: argument of type 'bool' is not iterable
```
because `newVal` is `False`.

fix: ensure the correct default defaultValue of a multiple/multi-lang `BooleanBone`

---

core/modules/file.py
core/tasks.py

Over time, pending FileSkeletons (datastore entities) can accumulate when upload urls have been requested but nothing has been uploaded. Therefore this adds the PeriodicTask `start_delete_pending_files` which deletes pending files older than 90 days.
To do the deletion safely on skeleton level a customization of the `DeleteEntitiesIter` was necessary. I see no reason not to use this for skeletons as long as you call the appropriate `.delete()` method.

feat: Delete old pending `FileSkeletons`

---

core/languages/de.py

The German translation of one "error"-Prompt for passwordBones was missing. Added it

fix: Missing german translation for "password too short" message

---

core/bones/boolean.py
core/bones/credential.py

This PR disallows construction of  `BooleanBone(multiple=True)`, which is pointless.

chore: Reject pointless `BooleanBone(multiple=True)`

---

core/modules/file.py
core/modules/formmailer.py
core/modules/user.py
core/prototypes/list.py
core/prototypes/singleton.py
core/prototypes/tree.py
core/render/json/__init__.py
core/securitykey.py
core/session.py
core/tasks.py

This is a draft for solving the problem of one session-based securitykey, making multiple requests in parallel impossible. This pull request partly replaces #704.
**Features:**
- a new securitykey is created every time it is requested
- securitykeys are bound to a session, if `session`-flag is True (default)
- unused securitykeys from a session are either being dropped on session kill, or when they became invalid
- Entire code refactoring for both securitykey and session module
- `/json/skey' accepts `amount`-flag for batch-mode skey requesting (decreases amount of requests)

feat: Rewrite of session-based securitykeys

---

core/render/html/env/viur.py

This fixes the problem, that renderPreparation is set in a Skeleton which is globally used by either Jinja or by normal module code, and both usages rely on other data types expected.
In my specific use-case where this bug arose, the following happened:
1. The template request current user via `{% set cuser = getCurrentUser() %}`
2. The template calls a `getList` function on a module
3. The module has a `canView()` function, which requests the user again
4. The `canView()` function expects `user["key"]` to be a `db.Key`, but it is a str, as it is modified by the `renderPreparation` setting. The code fails.
To be honest, this `renderPreparation` junk is a mess. We should either get rid of it or find a better solution.

fix: Clone `current.user` for use with Jinja

---

core/bones/numeric.py

This PR fix the problem when a `numericBone` is refreshed the value would be overwritten with `None`. If the value is already a `int/float`.

fix: Add missing fallback for `NumericBone.refresh()` destroying valid data

---

core/skeleton.py

This PR change the calculation of the `creationdate` and  `changedate` from `performMagic` to the newer `compute`.
I the future we can discuss to remove the `performMagic` function completly.

feat: Compute `creationdate` and `changedate` with the new `compute`-feature

---

core/config.py
core/email.py

It is now possible to set recipients for admin emails via config `conf["viur.email.admin_recipients"]`. Otherwise all root users are still addressed. By using `normalize_to_list` and its enhancement, a method as value is also possible. This allows e.g. dynamic recipient selections like own `UserSkel` queries. Also `conf["viur.email.recipientOverride"]` is now callable.

Make recipients for `sendEMailToAdmins` configurable

---

core/bones/date.py

_Originally posted by @sveneberth in https://github.com/viur-framework/viur-core/pull/733#discussion_r1263866264_
This doesn't work for me.
```py
[2023-07-14 17:25:28,483] viur/core/request.py:300 [ERROR] '_PytzShimTimezone' object has no attribute 'key'
File "/...deploy/viur/core/request.py", line 275, in processRequest
self.findAndCall(path)
File "/...deploy/viur/core/request.py", line 631, in findAndCall
res = caller(*newArgs, **newKwargs)
File "/...deploy/viur/core/prototypes/list.py", line 213, in edit
return self.render.edit(skel)
File "/...deploy/viur/core/render/json/default.py", line 212, in edit
return self.renderEntry(skel, action, params)
File "/...deploy/viur/core/render/json/default.py", line 152, in renderEntry
vals = …
```

fix: guessTimeZone() fails with Python 3.11

---

src/viur/core/modules/user.py

This PR fix the problem with the skey for the email verification process. 
The skey is created with `session_bound=True` but later checked with `session_bound=False` an this fails.

fix: Add 'session_bound=False' for the skey

---

src/viur/core/render/html/env/viur.py

This PR extends the function `renderEditForm` with the parameter `bones`. If this is set, only the bones that are in the list will be rendered.

feat: Add bones parameter for renderEditForm

---

src/viur/core/bones/password.py

This PR sets the `test_threshold` to 4, so by default the password must be 8 characters long and pass 3 out of 4 tests.
In addition, the `test_threshold`  is now also output in the structure

fix: Set test_threshold to 4 and add test_threshold to structure

---

src/viur/core/module.py

This is a replacement for #825

fix: `Method.__name__` improves #800

---

src/viur/core/prototypes/list.py
src/viur/core/prototypes/singleton.py
src/viur/core/prototypes/skelmodule.py
src/viur/core/prototypes/tree.py

This pull requests refactors the code for all prototype standard actions as follows:
- Consequent use of "key" in signature
- Clean-up kwargs check
- Clean-up "bounce" check
- Make code more readable
- Instanciate variables right before their use, and not on top

refactor: Prototype action functions

---

src/viur/core/decorators.py
src/viur/core/module.py
src/viur/core/prototypes/list.py
src/viur/core/prototypes/tree.py
src/viur/core/request.py

This pull requests does implement the following:
- Perform str to specific type parsing based on annotations for `@exposed` functions
- Report any required values which are unset, also with / and * Python-functions
- Removes any old stuff regarding parameter parsing and TypeError handling

feat: Extend `Method` to examine function signature and parse type annotations

---

src/viur/core/module.py
src/viur/core/modules/file.py
src/viur/core/request.py

The Method-interface and the new @skey decorator require that the security key is only validated on the first Method call, and not afterwards or below.

feat: Avoid multiple CSRF-security-key validation

---

src/viur/core/modules/user.py

fix: Add default value for `token` in `GoogleAccount.login()`, otherwise the process cannot be started

---

src/viur/core/__init__.py
src/viur/core/request.py
src/viur/core/session.py

Initial commit, refactor of BrowseHandler to Request. This is a first attempt to refactor this module without doing too big changes.
Contexts are already used in several ViUR projects to turn requests into a specific data environment. Context-parameters are preceded by an "@". This can be changed to a dynamic or customizable version in a next release.
This behavior is wanted:
- Request.kwargs contains all kwargs (because of backward compatibility)
- caller(kwargs) is a filtered kwargs without contexts
- Request.contexts contains only contexts

refactor: Refactor `Router` + collect context-variables to `Router.context`

---

src/viur/core/render/html/env/viur.py

There was a name conflict between the imported `qrcode` package and the jinja function `qrcode`.
```py
[2023-09-08 21:37:26,287] main.py:119 [ERROR] 'function' object has no attribute 'make'
[...]
{{ qrcode(otp_uri) }}
File "/project/deploy/viur/core/render/html/env/viur.py", line 742, in qrcode
return qrcode.make(data, image_factory=qrcode.image.svg.SvgPathImage, box_size=30).to_string().decode("utf-8")
AttributeError: 'function' object has no attribute 'make'
```

fix: import qrcode's element with an alias

---

src/viur/core/modules/user.py
src/viur/core/render/html/env/viur.py
src/viur/core/render/html/user.py

- The methods `second_factor_add` and `second_factor_add_success` are generic. So their template name should also be generic and not include `"otp"`.
- Since the above methods are general, it must be known for which concrete 2nd factor they are currently rendered. So the `name` and `action_name` are missing.
- Rendering the method `second_factor_choice` without specifying `second_factors` makes no sense. So the parameter should not be keyword-only.
- Add `add_url` in `second_factor_add` where data should be POST to.

fix some mixed up and blurred methods and concepts.

---

src/viur/core/module.py
src/viur/core/modules/user.py

This is only a suggestion. Please comment for any ambiguity or improvement. We can also remove /user/edit/self completely, or make "self" a mandatory parameter, so that "/user/view" or "/user/edit" are not allowed without parameters.

fix: Clean-up user/view and user/edit with "self"

---

src/viur/core/modules/user.py
src/viur/core/render/html/user.py

Look for the attribute `second_factor_choice_template` in the current renderer or the parent module (`user` module) and use it's value. By default this should be `"user_second_factor_choice"`.

fix: template name should not be static.

---

src/viur/core/module.py

This is a further improvement on the new argument parsing, which respects allow_empty=True for @skey, also when **kwargs are accepted. The previous implementation was incomplete.

fix: Additional fixing for `@skey(allow_empty=True)`

---

src/viur/core/__init__.py

In favor of pull request #859, the advise of importing decorators from `viur.core.decorators` that was introduced during 3.5 development is removed again, to pave its way.

fix: Remove `viur.core` decorator import advise

---

src/viur/core/__init__.py
src/viur/core/config.py
src/viur/core/request.py

Removes the defaults for `conf["viur.debug.traceExternalCallRouting"]` and `conf["viur.debug.traceInternalCallRouting"]`, which where removed by previous refactors.

fix: Reactivate old-style `trace*CallRouting` for backward compatibility

---

src/viur/core/request.py

This is not consistent with the `buildApp`. In the `viur.mainResolver` modules like `sub1.sub2.foo2` are added but cannot be routed.
See https://github.com/viur-framework/viur-base/pull/112#pullrequestreview-1629315674

fix: Remove replace of `.` to `_`

---

src/viur/core/config.py
src/viur/core/request.py

Normally only the `status`, `name` and `description` are logged. If you enable `conf["viur.debug.trace"] = True` you will also get a stack trace to see who raised it.

Add logging for raised `HTTPException`

---

src/viur/core/__init__.py

The default case of `email.sendEMailToAdmins` needs the intiantiated `user` module to get the root users as recipients. But at this point the `conf["viur.mainApp"]` wasn't set. This moves it below and disables the mail for dev_appserver when cloud logging is disabled.

fix: Move warning-email "Debug mode enabled"

---

src/viur/core/prototypes/tree.py

fix: Re-add missing `skel.fromDB()` in `Tree.move`

---

docs/Pipfile
docs/Pipfile.lock
docs/requirements.txt

after an major update of `astroid` from `2.15.6` to `3.0.0` crashed our rtd build process:
```py
File "/home/docs/checkouts/readthedocs.org/user_builds/viur-core/envs/develop/lib/python3.10/site-packages/sphinx/events.py", line 96, in emit
results.append(listener.handler(self.app, *args))
File "/home/docs/checkouts/readthedocs.org/user_builds/viur-core/envs/develop/lib/python3.10/site-packages/autoapi/extension.py", line 153, in run_autoapi
if sphinx_mapper_obj.load(
File "/home/docs/checkouts/readthedocs.org/user_builds/viur-core/envs/develop/lib/python3.10/site-packages/autoapi/mappers/python/mapper.py", line 300, in load
data = self.read_file(path=path, dir_root=dir_root)
File "/home/docs/checkouts/readthedocs.org/user_builds/viur-core/envs/develop/lib …
```

fix(docs): Add and lock all docs dependencies

---

src/viur/core/request.py

This is only for local development, but spams the log.

fix: Downgrade debug level for emulated deferred tasks

---

src/viur/core/request.py

As the context-member is not widely used yet, it should be fixed here to become useful in all projects using contexts, soon.

fix: Remove `@`-marker from request context destillation

---

src/viur/core/request.py

Readd `self` for kwargs. Fix https://github.com/viur-framework/viur-core/pull/884

fix: Readd self for kwargs in request `_route`

---

src/viur/core/securitykey.py

Under some circumstances, it is not wanted to index all properties stored behind a security key. Therefore, the `indexed`-parameter was added to the standard.

feat: Provide `indexed`-parameter to `securitykey.create`

---

src/viur/core/email.py
src/viur/core/modules/user.py
src/viur/core/tasks.py

This prefixes the project's ID to every mail sent via `email.sendEMailToAdmins`, which helps to identify the project where the error occurs, especially when the same sib-credentials are used by multiple projects.

fix: Prefix `project_id` to all admin emails

---

src/viur/core/modules/user.py

Fix / Followup for #881. Now the `action_url` and so on are send over the `params` parameter.

Fix: Second Factor `start`

---

src/viur/core/skeleton.py

This implements a standard `name`-bone holding the key of the skeleton as fallback. This automatically adds `name` to all Skeletons and fills the gap of the missing "$(dest.name)"-formatstring provided to RelationalBones by default.

feat: Provide computed `name`-bone for `Skeleton`

---

src/viur/core/skeleton.py

KeyBone is by default `readOnly=True` and `visible=False`. Also, generally enforce capitalization for nouns.

fix: Clean-up Skeletons `key` default bone

---

src/viur/core/skeleton.py

When trying to access an not existing attribute of a `SkeletonInstance` such as `skel.foo` an `KeyError` was raised. But an `AttributeError` should be raised instead.
This unpythonic behavior results in a bug when calling the periodic cron tasks: We've a module which that has a `db.Query` with `srcSkel` saved to it's instance, to use it for `Pagination`. On this `SkeletonInstance` the `in dir(...)` condition fails:
```py
File "/layers/google.python.pip/pip/lib/python3.10/site-packages/viur/core/request.py", line 276, in processRequest
self.findAndCall(path)
File "/layers/google.python.pip/pip/lib/python3.10/site-packages/viur/core/request.py", line 636, in findAndCall
res = caller(*newArgs, **newKwargs)
File …
```

fix: Raise an `AttributeError` in case of `KeyError` in `SkeletonInstance.boneMap`

---

src/viur/core/session.py

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#secure, and in combination with SameSite=none, Secure must be set, and is ignored on localhost since Chrome 89 and Firefox 75.
The disabling of `Secure` on local development server is therefore source for blocked cookies in combination with `SameSite`, and shall be removed.

fix: Always set `Secure` mode for session cookie

---

src/viur/core/module.py

A generator object is not JSON serializeable and `dumpConfig` fails

fix: `access` in method description must not be a generator object

---

src/viur/core/render/json/default.py
src/viur/core/render/json/user.py
src/viur/core/render/vi/__init__.py

I want to translate our repo names, the `CustomJsonEncoder` can resolve the `translate` objects. Just in case I've added this class where it could make sense to have translated objects too.

feat: use `CustomJsonEncoder` class in `json.dumps` call

---

src/viur/core/bones/credential.py
src/viur/core/bones/string.py
src/viur/core/bones/text.py
src/viur/core/render/json/default.py
src/viur/core/utils.py
tests/test_utils.py

Replace all `maxLength` with `max_length` and a backwards compatible check with a warning.

refactor: Rename `StringBone`'s `maxLength` into `max_length`

---

src/viur/core/bones/string.py

This PR fixes the problem that the value was always shortened to the maximum length before it was checked for the maximum length and so you simply lose data without getting an error message

fix: Invalid `maxLength` check in `StringBone`

---

src/viur/core/bones/__init__.py
src/viur/core/config.py

The line which caused the deprecation should be printed, not the line where the the `warn` call is done.

feat: Add stacklevels to `warning.warn` calls

---

src/viur/core/skeleton.py

Otherwise one don't know which bone caused the error during `toDB`

feat: Add logging with the name of the bone where the serialization failed

---

src/viur/core/tasks.py

During warmup `current.request` is `None` on local devserver. This patch adds another fallback

fix: `@retry_n_times` does not work on local server during warmup

---

src/viur/core/request.py

If a deferred task fails, the entire request will fails. To run most tasks as possible this patch adds an `try`/`except` block around each call.

fix: Add `try`/`except` around task emulation call

---

src/viur/core/modules/user.py
src/viur/core/securitykey.py

Resolve #796 as follow-up of #764
Before #764 the marker was `staticSessionKey`, but that wasn't PEP8. And since that has already been changed, I am using a new name, which IMO is better understood as a constant marker.

refactor: static skey marker

---

src/viur/core/tasks.py

I looks like if there's is a falsy member in a module, the entire search starts again at main_app.

fix: Start explicit with `main_app` in `findBoundTask()`

---

src/viur/core/session.py

`SameSite=None` requires `Secure` and modern browsers can ignore `Secure` (see #931) but `requests` doesn't ignore `Secure` of a cookie (see #949).
Therefore the consequence is to disable `SameSite` on localhost (which means the default `lax` is used) and obmitting the Secure attribute.
---
To reproduce the problem after #931 you can use this script:
```py
import requests
with requests.Session() as sess:
for i in range(3):
r = sess.get("http://localhost:8080")
print(r.cookies)
print(sess.cookies)
```
Before (current main, v3.5.7):
```py
<RequestsCookieJar[<Cookie viur_cookie_my-project=a0I9Y9smrNnk5qKDIuuC4vaANDRxH60LtOqjm8LYXL for localhost.local/>]>
<RequestsCookieJar[<Cookie viur_cookie_my-project=a0I9Y9smrNnk5qKDIuuC4vaANDRxH60LtOqjm8LYXL for localhost.local/>]> …
```

fix: disable cookie's `SameSite` and `Secure` for local server

---

src/viur/core/bones/password.py
src/viur/core/modules/user.py

- Provides default `descr`
- Cleans up RefSkel and Skeleton in system's User module
- Refactores some parts of PasswordBone for new syntax
- No functional changes

feat: Improved and slightly refactored `PasswordBone`

---

src/viur/core/modules/user.py

Implements a hook that is called whenever the password authentication was successful. It allows to perform further steps in custom UserPassword authentications.
The login process should be interruptible, so that custom modules can provide additional steps before  `continueAuthenticationFlow` is being called.
In my custom implementation, `on_login` is overwritten as follows:
```py
def on_login(self, user_entry):
if user_entry["password_enforce_change"]:
logging.info("Require password change")
return self.new_password()
return super().on_login(self, user_entry)
```
Without this hook, I need to copy the entire `login`-function and inject my custom code before the `continueAuthenticationFlow` call. Please respect this implementation, it works fine.

feat: Provide `UserPassword.on_login()` hook

---

tox.ini

VSCode updated its Python plugin to not cover pycodestyle as linter. Therefore, moving to e.g. flake8 is required, but flake8 does not recognize pycodestyle settings.
Did several tests to get it work with just one setting, but no way currently.

fix: Adding linter settings for flake8 as well

---

src/viur/core/config.py
src/viur/core/modules/user.py

Refactoring and hotfix for this traceback, when `conf["viur.user.google.gsuiteDomains"]` was not explicitly set before.
```
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/core/request.py", line 298, in _process
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/core/request.py", line 548, in _route
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/core/module.py", line 299, in __call__
return self._func(self._instance, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/core/modules/user.py", line 600, in login
if userInfo.get("hd") …
```

fix: Undocumented and uninitialized `conf["viur.user.google.gsuiteDomains"]`

---

src/viur/core/skeleton.py

Sometimes you want to perform skeleton related actions like `skel.view_url`. `@property`s  are a nice way for this.
Example:
```py
class ExampleSkel(Skeleton):
@property
def test_property(self):
return f'test_property of {self.__class__.__name__} {self.key} {self["key"]}'
```

feat: Implement `@property` support in `Skeleton`s

---

src/viur/core/tasks.py

The logging statement was on the correct position, but not `raise errors.Forbidden`

fix: Broken use of tasks emulator in combination with the app_server

---

src/viur/core/modules/file.py

Now we keep transparency in generated thumbnails if needed

fix: handling alpha channel within thumbnail generation if icc profile is present

---

src/viur/core/config.py
src/viur/core/render/vi/__init__.py

The vi-admin expects "moduleGroups" in `/vi/config`: https://github.com/viur-framework/vi-vue-components/blob/b7d21dacb93003bbf85f89ee51f3e0ec2f9433c6/components/screens/TheMainScreen.vue#L113
This patch add the related conf variable and ensures the value will be available under the old name (and the new, as in the conf itself: `admin.module_groups`).
Regression of #979

fix: Provide "moduleGroups" in `/vi/config`

---

src/viur/core/module.py

This fixes #933 while the fix #952 doesn't work.
`hasattr(self, key)` is implemented as "do a `getattr` if this doesn't raise an `AttributeError`, the attribute must exist". So the property will be accessed anyway, which is a problem if it contains code which doesn't work during warmup (because there is not request), like accessing `current.session.get()["my_value"]` (it's `None`).

fix: `@property` in module causes problems during warmup

---

src/viur/core/skeleton.py

This pull request modifies `ViurTagsSearchAdapter` to the following defaults:
- `min_length` to 2, as some names and words are already made of 2 characters
- `max_length` to 50, as longest non-fictive words in the world are having at least 45 characters. This is "pneumonoultramicroscopicsilicovolcanoconiosis" in English (45 chars) and "Rechtsschutzversicherungsgesellschaften" (39 chars) in German. The german fictional word "Donaudampfschifffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaft" has 80 chars, but we ignore this here.
- `substring_matching` should default to False, as all of our current software projects, substring_matching=True as its implemented here is not wanted or is wanted to be changed.

fix: Finetuning `ViurTagsSearchAdapter` defaults

---

src/viur/core/modules/user.py

Provides a way to customize the error message used when there is no other 2nd factor configured to the user who wants to login.

fix: Provide `User.msg_missing_second_factor` customization

---

src/viur/core/bones/key.py

fix: Add check for `db.Key` in `KeyBone.singleValueFromClient`

---

src/viur/core/bones/record.py
src/viur/core/skeleton.py

Some necessary improvements to `RelSkel.fromClient()` and `BaseSkeleton.fromClient()` for integration with the new vi-admin.
- RelSkel.fromClient() is valid when no data is provided and all fields are not required
- errors are now being iterated only once
- better "incomplete" detection
- comments (huh, woooow!)
- removed `allowEmptyRequired`-parameter from all functions as it is not necessary anymore
- tested against normal bones, RelationalBones with using skel, and RecordBones with several bone configurations

fix: Improve and refactor `BaseSkel.fromClient()` to handle empty/unset data

---

src/viur/core/prototypes/tree.py

`rootNode` is neither snake_case or a boolen (`=1`).
In `viur-shop` I use the bone `is_root_node`: https://github.com/viur-framework/viur-shop/blob/eacfb4a9e5288d3f3b5bf4c0b6445657cb48ff3b/src/viur/shop/skeletons/cart.py#L79
* It's snake_case
* a BooleanBone
* and `is_` is describing a state. You could also think that the bone rootNode points to a rootnode as relation.

feat: Add and improve check on root node in `Tree` prototype

---

src/viur/core/render/vi/__init__.py

Only `/vi/` should redirect, in case of `/vi/usre` (typo) it should raise an error (404) instead of redirection.
Resolves #787 
Alternative to #955

fix: Get rid of the catch all index behavior in vi renderer

---

src/viur/core/modules/user.py

This pull request improves the `UserPassword.pwrecover` function to the following:
- Errors turned into HTTP-error-codes
- Step 2 becomes Step 3, and Step 2 is optional, as it can either be resolved by a link in the e-mail, or by a code that is prompted for. It depends on the project. This proposal is action-skel based, and backward-compatible to the previous implementation.
- Moved all texts into the action itself, and cleaned unused text away.

fix: Make `UserPassword.pwrecover` ready for action-skels

---

src/viur/core/prototypes/list.py
src/viur/core/prototypes/tree.py

Since decades, it is not possible in the standard ViUR system to recursively copy trees or subtrees of a tree or hierarchy with a standardized method. This feature now implements a default recursive clone function, together with a clone-action.
The reason for a separate action is, that the clone-action can be customized (using the cloneSkel defined here), and introduces the new action-concept which will be hopefully prototyped soon in a backward compatbile manner.
This pull request is a replacement for parts of PR #829, implementing the following:
- Provides `clone`-actions for `List` and `Tree` prototypes
- Provides `cloneSkel`, `onClone` and `onCloned` hooks; Yes, this is in contrast to [the comment here](https://github.com/viur-framework/viur-core/pull/972#issuecomment-1845301188), …

feat: `clone`-action for `List` and `Tree`, recursive tree cloning

---

src/viur/core/languages/de.py
src/viur/core/modules/moduleconf.py
src/viur/core/modules/script.py

Adds Scriptor Scripts to the moduleconf:
The relation set in the moduleConf is responsible for the display and behavior of the scriptor action.
- name and icon:  are responsible for the appearance of the button in the admin.
- capable: describes the behavior in the admin
- access: to whom the button should be displayed in the admin. In addition, the admin checks whether all rights of the script are also fulfilled

feat: Provide script configuration in `ModuleConf`

---

src/viur/core/render/vi/__init__.py

The viur-shop has it's modules as submodules under a main `shop`. As you can see [here](https://github.com/viur-framework/viur-shop/blob/191b6a56e764a709170bcd1e3f1e27f1e3fa4c1b/src/viur/shop/shop.py#L45-L53).
So for example we have this path `/shop/address/list`.
It's perfectly routeable, but the vi doesn't know it because submodules are not collected. This PR adds a recursive walk through all the modules and collects them in `/vi/config`.

feat: Collect modules recursivly in `vi/config`

---

src/viur/core/tasks.py

Fix error caused by #1004.
Error: 
```shell
File "/home/foo/Schreibtisch/work/foo-dev/viur/src/viur/core/tasks.py", line 342, in _validate_request
if require_cron and "X-Appengine-Cron" not in req.request.headers:
^^^^^^^^^^^
File "/home/foo/.local/share/virtualenvs/foo-lcuCThDg/lib/python3.11/site-packages/webob/request.py", line 1410, in __getattr__
raise AttributeError(attr)
AttributeError: request
```

fix:  `_validate_request` in `tasks`

---

src/viur/core/bones/text.py
src/viur/core/modules/file.py
src/viur/core/render/html/env/viur.py
src/viur/core/render/json/default.py
tests/main.py

Accidently committed a wrong import, I was on this before. This fixes the use undefined ServiceAccountCredentials in download.
Additionally does further refactoring:
- All former `utils` functions are added to the `File` class as `@staticmethods`
- The `previous core.bones.text.parseDownloadUrl` is reborn as a heavily revised and now secure version as `File.parse_download_url()` (the previous version didn't take a few security-relevant cases into account).
- Also found a regression: call to `downloadUrlFor` that was being renamed and moved in #1046 already

fix: Further refactoring and fixing of `File`-module for #1046

---

src/viur/core/bones/relational.py

This fixes the bug that comes up when there are two RelationalBones with `RelationalConsistency.PreventDeletion` being set to the same target kind. It raises an error 500 on a customer project, as the assertion and helpful "PROGRAMMING ERROR DETECTED" message are raised, which causes that this bug arose.

fix: `RelationalBone` locking bug

---

src/viur/core/utils/__init__.py

It caused
```py
'super' object has no attribute '__getattr__'
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/core/request.py", line 298, in _process
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/core/request.py", line 554, in _route
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/core/module.py", line 299, in __call__
return self._func(self._instance, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspace/modules/file.py", line 112, in static
signed_url = utils.downloadUrlFor(
^^^^^^^^^^^^^^^^^^^^
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/core/utils/__init_ …
```

fix: Use `__getattribute__` instead of `__getattr__` for super call in utils

---

CHANGELOG.md
src/viur/core/modules/user.py
src/viur/core/tasks.py
src/viur/core/version.py

Already released as v3.5.14 and tested in a live environment.

fix: `current.user` unset in deferred task calls

---

src/viur/core/prototypes/list.py
src/viur/core/prototypes/singleton.py

Ever wondered why every module you want to access by URL without specifying a renderer throws out an error message like this?
Well, this pull requests removes the inconsequent `Prototype.html = True` from the `List` and `Singleton` prototype. The `Tree` prototype was always not by default visible to the html-render.
This is how the same call is rendered now:
Normally, all modules being visible to the standard html render have a `Module.html = True` on the bottom. Therefore, this little change wouldn't break too much. I'm also of the opinion, that it is a security issue.

fix: Remove default `P.html = True` from prototypes

---

src/viur/core/bones/text.py
src/viur/core/email.py
src/viur/core/modules/moduleconf.py
src/viur/core/modules/user.py
src/viur/core/request.py
src/viur/core/session.py
src/viur/core/tasks.py

Make ViUR, especially the user system runable again after the _extremely_ security-relevant and _non-breaking_ PR #1037

fix: Make ViUR runable again after the extremely security-relevant PR #1037

---

src/viur/core/modules/user.py

Since #1078 we can use datetime.timedelta as duration. So we shoud use it.

refactor: Replace securitykey duration with `timedelta`

---

src/viur/core/config.py
src/viur/core/render/vi/__init__.py
src/viur/core/request.py

This is an extension to #1085 which both allows to use `vi/user/login` as the replacement for `vi/user/getAuthMethods` and generalizes the access verification based on the config.
Also adds `path`-member to Router/Request.

fix: `vi.canAccess` based on fnmatch config setting

---

src/viur/core/utils/__init__.py

- Removed unused imports
- Cleaned imports
- Added deprecation fallbacks for `downloadUrlFor` and `srcSetFor` as some projects make use of these

fix: Improving `utils` deprecation handling

---

CHANGELOG.md
src/viur/core/modules/user.py
src/viur/core/version.py

The `File`-module has default setting "add", "edit" for editor-role, which didn't work. One correction would be to simply add "view" there, but this method automatically adds "view" when "edit" or "delete" is given.

fix: User roles: Automatic "view" right when "edit" or "delete" is provided

---

src/viur/core/config.py
src/viur/core/request.py

Remove the static filter that removes any parameters passed, starting with "_", to a configurable filter function which provides more flexibility.

fix: Improvement `conf["viur.paramFilterFunction"]`

---

CHANGELOG.md
src/viur/core/modules/user.py
src/viur/core/version.py

Login causes error 500 when e.g. umlauts are being used.

fix: Handle non-ASCII characters in username comparison

---

src/viur/core/prototypes/list.py
src/viur/core/prototypes/skelmodule.py
src/viur/core/prototypes/tree.py

e.g.:
```py
default_order: DEFAULT_ORDER_TYPE = (
("firstname", db.SortOrder.Ascending),
("lastname", db.SortOrder.Ascending),
)
```

feat: `default_order` should support multiple orders as well

---

src/viur/core/bones/password.py
src/viur/core/modules/user.py

- Implements action skel `LoginSkel` correctly with the right action
- Modifies PasswordBone to not render tests when test_threshold is set to 0, which is a security improvement, as it is not rendered to non-authenticated users

feat: Provide `LoginSkel` on `UserPassword.login`

---

src/viur/core/render/json/default.py
src/viur/core/render/xml/default.py

>There's still no difference between False and None.
(https://github.com/viur-framework/viur-core/issues/1096#issuecomment-1999974027)
With this PR it's fixed.

fix: Add `is None`-check for bone values with languages

---

src/viur/core/modules/user.py

This was an untested part of changes with pull request #997.

fix: `TimeBasedOTP.start()` should use UserSkel

---

src/viur/core/bones/json.py

Otherwise the bone is indexed and crashes at the 1500 bytes index limit in case of large data

fix: Pass arguments in `JsonBone.__init__()` to `super()` call

---

src/viur/core/bones/__init__.py
src/viur/core/bones/base.py
src/viur/core/bones/select.py
src/viur/core/skeleton.py

Currently only the label is used as `translation` key, but also not in
every case. This PR changes allows to set a custom prefix or use a
included method to generator a prefix from the skeleton and bone name.
Furthermore context is added via translation hint.
This is especially interesting for enums, where you cannot set a custom label.

    feat: Implement `translation_key_prefix` for `SelectBone` values

---

src/viur/core/tasks.py

Calls the `@CallDeferred` decorated method directly. This is for example necessary, to call a super method which is decorated with `@CallDeferred`.

fix: Add param `_call_deferred`

---

src/viur/core/prototypes/list.py
src/viur/core/prototypes/tree.py

The current default_order caused, that entries didn't show up when there was a name-bone which had a languages-setting, so it needed to be manually corrected to e.g. `name.de`. This PR fixes the behavior to either use the current or the first language. Its still possible to redefine default_order in any style like befor.

fix: Improve `List.default_order` to respect languages config

---

src/viur/core/tasks.py

We popped the value from kwargs, with the default `None`. So in `tasksargs` there was always a value (at least the `None`), therefore the default value `conf.instance.app_version` of `taskargs.get()` was never used (but it should be the default case).

fix: target_version was always `None` (used the default version)

---

src/viur/core/skeleton.py

This bug came up when I did this:
```py
class UserSkel(UserAbstractSkel):
brand = None  # don't provide a brand bone
```
Importing the UserAbstractSkel caused that all bones of that Skeleton where initialized, althought it is set to None within the subclass. This causes bone-objects in memory which are never used by nothing.

fix: Avoid `*AbstractSkel`s from being initialized

---

src/viur/core/modules/file.py

Otherwise I get locally and in the cloud this error:
```py
[2024-04-12 20:21:50,559] /.../viur/core/tasks.py:248 [ERROR] module 'PIL' has no attribute 'ImageCms'
File "..lib/python3.11/site-packages/viur/core/tasks.py", line 244, in deferred
_deferred_tasks[funcPath](*args, **kwargs)
File ".../site-packages/viur/core/bones/file.py", line 58, in ensureDerived
callRes = callee(skel, skel["derived"]["files"], params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ".../site-packages/viur/core/modules/file.py", line 114, in thumbnailer
src_profile = PIL.ImageCms.ImageCmsProfile(f)
^^^^^^^^^^^^
AttributeError: module 'PIL' has no attribute 'ImageCms'
```

bug: Add import of `PIL.ImageCms`

---

src/viur/core/session.py

Resolves https://github.com/viur-framework/viur-shop/blob/f6e84e772be01d7cf2beb74d674a3aeda6ac303b/src/viur/shop/modules/abstract.py#L45

feat Add session `setdefault`

---

src/viur/core/prototypes/list.py
src/viur/core/prototypes/tree.py

When a list function is provided with invalid data, e.g. a non-base64-key, the `queries`-member of a `db.Query` is set to None, which causes failures with the default order feature.

fix: `list` should handle unsatisfiable queries

---

src/viur/core/render/vi/__init__.py

With viur-cli v2 the vi-admin moved from `/deploy/vi/` to `/deploy/admin/`. Therefore the redirect from `HOST/vi` to `HOST/vi/s/main.html` does no longer work. Now we have to check both path.
(We could make this configurable in 3.7 ...)

fix: Support `/deploy/admin` folder as well

---

src/viur/core/modules/script.py

When providing permalinks to Scriptor scripts across multiple projects, it's better to either use the path of the script rather then the key. This is also useful for the script runner and for scriptor actions integrated somewhere.
Additionally allows to view a script by its path, e.g. `http://localhost:8080/json/script/view/leaf/export.py` or `http://localhost:8080/json/script/view/leaf?key=folder/sub/result.py`

feat: View script by path

---

src/viur/core/request.py

Follow-up on #1157, fixes #1063

fix: Don't obfuscate any route with character replacements

---

LICENSE
README.md
setup.cfg
src/viur/core/__init__.py

In the viur-meeting on 2024-04-12, it was decided to change the licensing terms of the viur-core component from the LGPL-v3 into the MIT license.
This pull request updates all relevant parts of the codebase.

Change of LICENSE from LGPL into MIT

---

src/viur/core/utils/json.py
tests/main.py

`db.Entity` was handled like a dict, and therefore the key was gone.

fix: `ViURJsonEncoder` doesn't handle `db.Entity`

---

src/viur/core/bones/text.py
tests/bones/test_text_bone.py

With the default option `convert_charrefs=True` the serializer replace HTML entities to Unicode (like `&nbsp;` to `\u00a0`). This PR disables this option.
Furthermore it adds some tests (which are adapted from `StringBone`).
fixes #1182

fix: Keep HTML-entities in `HtmlSerializer`

---

src/viur/core/modules/moduleconf.py
src/viur/core/prototypes/list.py
src/viur/core/prototypes/tree.py

Hotfix for a special error that occured with the ModuleConf-module when the authenticated user is NOT root, viur-core failed with error 500.
The data formats used by viur-datastore are a heavy mess and must be clarified asap.

fix: `default_order` and `query.queries` can be a list

---

src/viur/core/logging.py

This fix the Problem that the logging explorer is filled with trash logs.
Like

fix: Add `google.cloud.logging_v2.handlers.transports.background_thread`  to the `EXCLUDED_LOGGER_DEFAULTS`

---

src/viur/core/render/abstract.py
src/viur/core/render/html/default.py
src/viur/core/render/json/default.py
src/viur/core/render/xml/default.py

feat: Implement abstract renderer

---

src/viur/core/prototypes/list.py

In the viur-meeting on 2024-06-21, it was desired that there shall be no default_order on "name" for List-modules.

fix: Remove `default_order` fallback from `List`

---

src/viur/core/bones/select.py
src/viur/core/config.py

This change should be considered and relates closely to viur-framework/vi-vue-utils#12.
To enable new style, add
```py
conf.compatibility.remove("bone.select.structure.values.keytuple")
```
to your main.py.

feat: Render `SelectBone` values in dict-style

---

src/viur/core/session.py

Fixes an endless recursion, this part of the new session was not tested before.

fix: `Session.__delitem__` causes endless recursion

---

src/viur/core/bones/record.py

The `if not bone.searchable` condition introduced in #528 due to refactorings was too much.
Without this fix, weak files are not locked and will be deleted.
Fixes #1211

fix: `RecordBone.getReferencedBlobs` should collect references for all bones

---

src/viur/core/bones/__init__.py
src/viur/core/bones/spam.py
src/viur/core/languages/de.py

Adds a simple math question as spam protection, that works without any third-party products.
We got a fine experience with this yet in several projects.
Requires #1208 to be fixed.

feat: Add `SpamBone`

---

src/viur/core/bones/base.py

I wondered why my bone descr aren't translated at the json renderer. The `translate` object was actually never created. It would work if I create it manually and pass it at `descr` argument, but this is not matching to the type hint. This PR fix these issues.
For reference, there are some notes which could expect a translate object:
https://github.com/viur-framework/viur-core/blob/104ac87cd92655a7aa084e182c7501dc42a5dcab/src/viur/core/bones/base.py#L168
https://github.com/viur-framework/viur-core/blob/104ac87cd92655a7aa084e182c7501dc42a5dcab/src/viur/core/bones/base.py#L1272

feat-fix: Wrap `descr` and `params.category` in `translate` object for auto translating

---

src/viur/core/email.py

For : 
https://github.com/viur-framework/viur-core/blob/5d1e14de32327d0d11c78cbaaa29de2d5ff8da33/src/viur/core/email.py#L63
https://github.com/viur-framework/viur-core/blob/5d1e14de32327d0d11c78cbaaa29de2d5ff8da33/src/viur/core/email.py#L481

fix: Add datetime import in email.py

---

src/viur/core/__init__.py
src/viur/core/prototypes/skelmodule.py

This is also a better implementation, as the previous checked for module name, but the kind name is the important one!

refactor: Move datastore index retrieval to `SkelModule`

---

src/viur/core/bones/base.py
src/viur/core/bones/record.py
src/viur/core/bones/relational.py

Fixes `MultipleConstraints`
- requirement for a hashed tuple
- renamed dataclass members*
- required modularization for `RelationalBone` and `RecordBone`
*) yes, this is a breaking change, BUT this feature isn't used in any ViUR project so far, I'm sure.

fix: `MultipleConstraints` as intended

---

src/viur/core/bones/relational.py

Don't write the "key" value, which is always None, into the src-property of `viur-relations`. The key is encoded into the embedded Entity and used this way everywhere, respective using `src.__key__` in queries.
This is only a minor bug, as it didn't influence that viur works properly, but it was annoying during debug.
Relates to #1236 + #1237

fix: null-key always written into `viur-relations`

---

src/viur/core/__init__.py
src/viur/core/prototypes/skelmodule.py

This is a back port of #1231 to core-3.6, as #1232 should become part of v3.6.
This is also a better implementation, as the previous checked for module name, but the kind name is the important one!

refactor: Move datastore index retrieval to `SkelModule` (backport v3.6)

---

src/viur/core/__init__.py

This is both a refactor and a fix for the `Modulename.html = True` default that was removed with viur-core 3.6.
The error `AttributeError: 'Index' object has no attribute '<modulename>'` is fixed with this improvement, and the workaround of `conf.main_app.vi.modulename` is not neccessary anymore.
Belongs to #1229, replaces #1232.

refactor: `__build_app` function clean-up and make all modules accessible

---

src/viur/core/skeleton.py

This change is for better debugging, but the process might still hang.
I'm quite unsure if this thing should better be ignored, or if `entry` itself should be removed, as it is an inconsistency.

fix: Inconsistency raises AssertionError

---

src/viur/core/bones/relational.py
src/viur/core/skeleton.py

You can set `consistency` on a `RelationalBone` to `RelationalConsistency.PreventDeletion` to disallow the deletion of the referenced Skeleton (if there is a relation from this bone to it).
This works fine as long a Skeleton is referenced by only few other Skeleton. But if thousands of Skeletons has a reference to the same Skeleton (10000:1 relation) the `viur_incomming_relational_locks` list has to hold 10000 keys, which exceeds the size limit of the entity. Furthermore the transaction limit would be exceeded during writing on 10000 entites the `"{bonename}_outgoingRelationalLocks"` property too.
We cannot carry a list, neither in the one way nor in the other. (Yes, okay, theoretically you could write _outgoingRelationalLocks outside the transaction, maybe in a task. But even here it can …

fix: Re-Implement `RelationalConsistency.PreventDeletion` validation

---

src/viur/core/bones/numeric.py
tests/bones/test_numeric_bone.py

Resolves #1234 (in some ways)
I actually wanted to make it possible to save large values. In the end, however, I found out that this is limited by the datastore. Due to a completely messed up implementation and bad error handling, I didn't recognise this. This PR now improves that.

fix: Improve `NumericBone.singleValueFromClient`

---

src/viur/core/__init__.py

This is still a hack, but it doesn't map any declared symbols like jinja global functions or imported stuff into the renderers-map as before.

fix: Cleanly collect renders from Python module

---

src/viur/core/bones/captcha.py
src/viur/core/bones/numeric.py
src/viur/core/config.py

* feat: Validates score of [reCAPTCHA v3](https://developers.google.com/recaptcha/docs/v3?hl=en) challenge
* feat: Add more verbose error messages
* feat: Add config option `captcha_enforce_always`
* change: Support bone name and "g-recaptcha-response" in `fromClient`
* refactor: Use `requests`
* docs: Update docstrings and describe behavior

feat: Improve `CaptchaBone`

---

src/viur/core/bones/spam.py

This is a regression introduced by #1227 causing descr() is called before a session is available.

fix: `SpamBone` regression of descr-property

---

src/viur/core/skeleton.py

This is a hotfix for the problem that `is_add` is being set based on if the key is set or not. Furthermore, it is determined twice, so that the "magic"-bullshit now was moved into the transaction. It is a fix for PR #973 but previous implementation was also wrong.

fix: `Skeleton.toDB()`s `is_add` determined wrong

---

docs/doc_tutorial/advanced/05_training_config.rst
pyproject.toml
src/viur/core/config.py
src/viur/core/email.py
src/viur/core/modules/formmailer.py
src/viur/core/modules/user.py
src/viur/core/skeleton.py
src/viur/core/tasks.py

This allows to store the credentials and other settings on the instance itself and reduce the config size.
Furthermore I think this is more pythonic, combines what belongs together and makes `abc` meaningful.
This a small **breaking change**.
Instead of 
```py
conf.email.mailjet_api_key = secret.get("api-mailjet-key")
conf.email.mailjet_api_secret = secret.get("api-mailjet-secret")
conf.email.transport_class = EmailTransportMailjet
```
you write now
```py
conf.email.transport_class = EmailTransportMailjet(
api_key=secret.get("api-mailjet-key"),
secret_key=secret.get("api-mailjet-secret"),
)
```
--- 
* Enforce pep8 compliant `snake_case` names as requested by @phorward 
* `email.sendEMail` is now `email.send_email`
* `email.sendEMailToAdmins` is now `email.send_email_to_admins`
* We use …

refactor: Send emails from `EmailTransport` instances instead of class

---

src/viur/core/modules/file.py
src/viur/core/modules/formmailer.py
src/viur/core/modules/moduleconf.py
src/viur/core/modules/page.py
src/viur/core/modules/script.py
src/viur/core/modules/site.py
src/viur/core/modules/translation.py
src/viur/core/modules/user.py

- Added some docstrings to common modules.
- Removed `[modulename].json = True` and `[modulename].html = True` default markers where not explicitly necessary

doc+fix: Added module docstrings, removed render defaults

---

src/viur/core/skeleton.py

This little function causes the ViUR system to break in different places, because a bone None-object cannot be procesed.
```py
def addSkel(self):
skel = super().addSkel().clone()
skel.status = None
return skel
```

fix: Delete bones set to `None` from a Skeleton

---

src/viur/core/module.py

- "root" is always allowed to pass
- the set().difference() method check didn't work as expected, therefore changed to an all(a in user["access"]) check.

fix: @access-decorator

---

src/viur/core/render/html/env/viur.py

Fix the error
```
File "/home/foo/.local/share/virtualenvs/bessershop-0UKlbQ2G/lib/python3.12/site-packages/viur/core/render/html/env/viur.py", line 638, in renderEditForm
categoryClassName="".join([x for x in category if x in string.ascii_letters]),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'translate' object is not iterable
```

fix: Cast category to str() for ascii check

---

src/viur/core/bones/json.py
src/viur/core/render/json/default.py
src/viur/core/utils/json.py

This PR is a fix for #1092 and makes SkeletonInstances now json serializable.
Like:
```python
def get_skel():
skel = conf.main_app.country.viewSkel()
skel.fromDB("agxoaWVyLWdpYnQtZXNyFQsSDm5pY2h0c196dXNlaGVuGLkKDA")
return skel
foo=JsonBone(compute=Compute(fn=get_skel,interval=ComputeInterval(ComputeMethod.OnWrite),raw=True))
```
Now get in json render 
```json
"c_s": {
"key": "agxoaWVyLWdpYnQtZXNyFQsSDm5pY2h0c196dXNlaGVuGLkKDA",
"name": null,
"creationdate": "2022-10-05T06:20:38+00:00",
"changedate": "2024-02-05T13:20:46+00:00",
"viurCurrentSeoKeys": {
"de": "4757066702913536",
"_viurLanguageWrapper_": true,
"en": "4757066702913536"
},
"country": "Nauru",
"continent": "Oceania",
"sortindex": 1664950838.329367
}
```

feat: Make SkeletonInstance json serializable

---

src/viur/core/bones/relational.py

singleValueFromClient is always a function working with str data. In this case, I wanted to provide a db.Key through a fromClient function, which raised an AssertionError. Why the heck. This always converts the key to a str. In case the key is invalid, if will fail later on.

fix: `RelationalBone.singleValueFromClient` str-cast

---

src/viur/core/modules/file.py
src/viur/core/render/html/env/viur.py

fix: handle gracefully downloadurls and srcsets with optional languages overwrite for files

---

src/viur/core/bones/base.py
src/viur/core/bones/file.py
src/viur/core/i18n.py
src/viur/core/modules/file.py
src/viur/core/modules/moduleconf.py
src/viur/core/modules/script.py
src/viur/core/modules/translation.py
src/viur/core/modules/user.py
src/viur/core/prototypes/list.py
src/viur/core/prototypes/singleton.py
src/viur/core/prototypes/tree.py
src/viur/core/render/html/env/viur.py
src/viur/core/skeleton.py

This pull request is a first, backward-compatible milestone on #630.

refactor: `Skeleton`-API rework

---

src/viur/core/render/html/env/viur.py

This PR makes fileSize deprecated and call `jinja2.filters.do_filesizeformat` instead.

feat: Make custom jinja filter `|fileSize` deprecated

---

src/viur/core/bones/text.py
src/viur/core/config.py
src/viur/core/modules/moduleconf.py

Provide the HtmlBone (TextBone) "validHtml"-default as a config variable, so it can be changed globally.
This feature is useful to some projects, and is a first improvement on the messy TextBone class.
Relates to and partly replaces #631.

feat: `conf.bone_html_default_allow`

---

src/viur/core/bones/base.py
src/viur/core/bones/boolean.py

Fix for #1178
and add check for  values in getdefaultValue.

feat: Add support for callable `defaultValue` in `BooleanBone`

---

src/viur/core/skeleton.py

See https://github.com/viur-framework/viur-datastore/blob/45deae60afad6699a518ab88ab0ead3771926376/src/viur/datastore/utils.py#L92
Discovered during testing of https://github.com/viur-framework/viur-core/pull/1267

fix: Calling `db.KeyHelper` with `None` raises a unhandled `NotImplementedError`

---

src/viur/core/bones/base.py

The language value needs to be a `list` as default value, not `None`.
A simple add failed already on unserialize:
```py
skel = ExampleSkel()
skel.write()
```
```py
[2024-10-10 02:06:18,911] viur/core/skeleton.py:1208 [ERROR] Failed to serialize Test_Bone_select_multi_lang <viur.core.bones.select.SelectBone object at 0x7fd69253ee40> {'de': None, 'en': None}
[2024-10-10 02:06:18,947] viur/core/request.py:331 [ERROR] ViUR has caught an unhandled exception!
[2024-10-10 02:06:18,947] viur/core/request.py:332 [ERROR] 'NoneType' object is not iterable
File "/.../deploy/viur/core/request.py", line 306, in _process
File "/.../deploy/viur/core/request.py", line 565, in _route
File …
```

fix: multiple bones with languages have the wrong default value

---

src/viur/core/skeleton.py

This is a fix for a regression #1259, fix for #1285

fix: `SkeletonInstance` must accept `bone_map` and deprecated `clonedBoneMap`

---

src/viur/core/bones/base.py

The previous test didn't work when I had the signature `*_` simply accepting and ignoring any parameters. This test is much better and versatile.

fix: Improved signature test on callable `defaultValue`

---

src/viur/core/config.py
src/viur/core/modules/user.py
src/viur/core/request.py
src/viur/core/securitykey.py
src/viur/core/session.py

This PR fix #1276.
1. Language is only stored in the Session when a Session exist. 
2. When no Session exists the `Accept-Language` Header is used to determine the language.
3. `clear`, `popitem`, `setdefault` added to the Session class
4. The Session is only fetched from db if a Cookie is provided

feat: Load Session only when needed

---

CHANGELOG.md
src/viur/core/bones/text.py
src/viur/core/modules/file.py
src/viur/core/version.py

Truly amazing that this bug has not yet surfaced in the entire, huge, worldwide ViUR community with its thousands of projects... wow. It seems that none of those millions or trillions of projects worldwide have ever saved a TextBone with a link to a local file.
```
[2024-10-15 22:55:09,930] /.../viur/core/request.py:331 [ERROR] ViUR has caught an unhandled exception!
[2024-10-15 22:55:09,930] /.../viur/core/request.py:332 [ERROR] too many values to unpack (expected 2)
File "~/myproject/.venv/lib/python3.12/site-packages/viur/core/request.py", line 306, in _process
File "~/myproject/.venv/lib/python3.12/site-packages/viur/core/request.py", line 565, in _route
File …
```

fix: `File.parse_download_url()`: `too many values to unpack`

---

CHANGELOG.md
src/viur/core/skeleton.py
src/viur/core/version.py

Fixes occured error `NotImplementedError: No handling for type(relVal)=<class 'NoneType'>`

fix: `Skeleton.processRemovedRelations` unable to handle empty values

---

src/viur/core/modules/user.py

This change avoids special-cases as described in #1082 and also fixes a little bug in the password recovery process. Closes #1082.

fix: Test `user["status"]` at one place

---

src/viur/core/config.py
src/viur/core/email.py

This adds the possibilty to set the sender once without touching every `send_email` call.
The sender order is now (Low to Hight):
- Use `conf.email.sender_default` as default
- Use `sender` from `send_email` call (if provided)
- Use `conf.email.sender_override` (if set)

feat: Introduce `conf.email.sender_default`

---

src/viur/core/bones/base.py

This PR fix the following bug:
If you have a relation in skeleton A to a skeleton B that has a compute bone with a lifetime. If you then call the skeleton A but the lifetime of the bone from the skeleton B is not included in the call because it is not in the RefKeys.

fix: Handle `RefSkel`s in `unserialize_compute` differently

---

CHANGELOG.md
src/viur/core/modules/user.py
src/viur/core/version.py

This hotfixes the bug that a skeleton inherited from UserSkel cannot be subSkel'ed, as an exception `TypeError: UserSkel.__new__() got an unexpected keyword argument 'bones'` occurs.
The above exception is from viur-core 3.7, but it will raise a similar exception in viur-core 3.6. I found this bug by porting a project from viur-core 3.5 directly to viur-core 3.7.

fix: `UserSkel.__new__()` cannot be subSkel'ed

---

CHANGELOG.md
src/viur/core/prototypes/list.py
src/viur/core/prototypes/tree.py

Ok... this is one of the most creepy things I've every made.
This pull request simplifies and fixes the `default_order`-feature introduced by viur-core 3.6, and also doesn't raise an unauthorized error on a MultiQuery, which is created from a `listFilter` that applies an "IN"-filter.
The bug is fixed, and the code is much more readable than before.

fix: `default_order`-code raises `errors.Unauthorized()` on MultiQuery

---

src/viur/core/skeleton.py

Due the changes in #1259, the cloning behavior was broken.
This pull requests fixes the following:
1. Any subskel'ed SkeletonInstance globally modified bones, as they where flagged as "cloned" but wheren't.
2. `SkeletonInstance.clone()` caused a sub-skel lose its boneMap, so it contained all bones again.
3. Renamed `full_clone` into just `clone` to make it more familiar with what it does. A `Skeleton.subskel(clone=True)` does now return a standalone clone of the skeleton which can be modified.
4. Deprecated `Skeleton.subSkel()` (camel-case) now accepts old `fullClone`-parameter again to stay backward compatible.

fix: `Skeleton.subskel()` and `SkeletonInstance.clone()`

---

src/viur/core/bones/key.py
src/viur/core/modules/file.py

This fixes above bug. Additionally, the "pendingparententry" value is set to None instead of False in `Skeleton.refresh()`, which is invalid.

fix: `KeyBone.singleValueUnseralize()` doesn't handle None

---

src/viur/core/render/html/default.py
src/viur/core/render/json/default.py
src/viur/core/utils/json.py

The function `db.encodeKey` does the same, and is obsolete. Didn't know it was deprecated.

refactor: Replace `db.encodeKey` by `str`-cast

---

src/viur/core/modules/user.py

Recent use cases have shown that the current logic is confusing, especially because it is only implemented in UserPassword.
If a user logs in with GoogleLogin but does not have sufficient rights, they are redirected back to the start page or the login page. When attempting to log in via UserPassword, the login attempt is immediately acknowledged with loginSucceeded(), and it is pretended that the login was successful - although no credentials were checked.
This is confusing and inconsistent. Removing this check allows to just login into a fresh session with the given credentials, and everything is more convenient.

fix: Remove check if logged-in in `UserPassword.login()`

---

src/viur/core/skeleton.py

This allows to use `__init_subclass__` with parameters

fix: Add `**kwargs` to skeleton meta classes

---

src/viur/core/skeleton.py

This PR fixes the bug when you clone a skeleton and then add a bone neither the name nor the skelcls are set for this bone.
```python
skel=self.viewSkel().clone()
select = SelectBone(values={"a":1})
skel.__setattr__("x",select)
return self.render.view(skel)
```
Produce
```
File "/viur/src/viur/core/bones/select.py", line 102, in __getattribute__
f"value {key} for {self.name}<{type(self).__name__}> in {self.skel_cls.__name__} in {self.skel_cls}"
AttributeError: 'NoneType' object has no attribute '__name__'.
```
Many thanks to @skoegl for the find and the report.

fix: Add `__set_name__` in `__setattr__` for bones

---

src/viur/core/module.py

People came up with the idea of using the available parameters ... Never noticed so far
https://github.com/viur-framework/viur-shop/blob/ff6ea1721c7e09f4c3a9cd3346541f071884c2fb/src/viur/shop/modules/api.py#L176
Please patch this in 3.7 and later as well.

feat: Support enum type

---

src/viur/core/modules/file.py

Returned None on valid dlpath.

fix: `File.parse_download_url()` handles dlpath wrong

---

CHANGELOG.md
src/viur/core/i18n.py
src/viur/core/modules/translation.py

This interface was already implemented in some projects, and was now cleaned and standardised. It allows to set translate()-objects to public, so that an unauthorized client can request them without further authentication.
The function /json/_translate/get_public was made available to dump translations.
Example calls:
- `/json/_translation/get_public` get public translations for current language
- `/json/_translation/get_public?languages=en` for english translations
- `/json/_translation/get_public?languages=en&languages=de` for english and german translations
- `/json/_translation/get_public?languages=*` for all available languages

feat: Public translations interface

---

src/viur/core/bones/spam.py

The spambone seems to consume its iteratore provided as default once. A second instance if SpamBone() raised a range-error, because `values` where empty. This fixes it.

fix: `SpamBone()` consumes default iterator once

---

src/viur/core/bones/base.py
src/viur/core/bones/spam.py

This bug is a regression of #1277 and #1227.
The `__system_initialized`-bool should be set *after* all setSystemInitialized() functions where invoked, as the system is defined to be initialized *after* the stuff where worked.
Otherwise, `SpamBone.descr` cannot determine whether it is executed in an uninitialized or initialized system.

fix: `SpamBone`'s descr not available without session

---

src/viur/core/bones/json.py

This PR fix the Bug that only `str` is validated by the JsonBone.
Example :
```python
testjson = JsonBone(schema={
"type": "object",
"properties": {
"price": {"type": "number"},
"name": {"type": "string"},
},
})
```
```python
print(skel.setBoneValue("testjson",{"name" : "Eggs", "price" : "invalid"}))
print(skel["testjson"])
```
```python
True
{'name': 'Eggs', 'price': 'invalid'}
```
>---
```python
print(skel.setBoneValue("testjson",json.dumps({"name" : "Eggs", "price" : "invalid"})))
print(skel["testjson"])
```
```python
False
{'name': 'Eggs', 'price': 1}
```

fix: `JsonBone` validate `object` and `list` too

---

src/viur/core/skeleton.py

If you create a new skel, call `toDB` and then access `skel.dbEntity` it was still None, this made problems with compute bones

fix: Store written db_obj in `toDB` on source skel

---

src/viur/core/modules/user.py

When the UserSkel has no status-bone, it should default to is_active=True.
It occured in a subskel, that didn't contain the "status"-bone, the default
```py
def onEdited(self, skel):
super().onEdited(skel)
if not self.is_active(skel):
session.killSessionByUser(skel["key"])
```
always kicks the user - just because the "status" bone was unavailable. The previous definition before #1309 was
```py
def onEdited(self, skel):
super().onEdited(skel)
if "status" in skel and skel["status"] < Status.ACTIVE.value:
session.killSessionByUser(skel["key"])
```

fix: `User.is_active()` without status-bone

---

src/viur/core/bones/relational.py

Fix the Bug that this fails when 
https://github.com/viur-framework/viur-core/blob/7801292f664957202bc14756d1d51b9ff917343d/src/viur/core/bones/relational.py#L1185-L1192
this returns `None`
https://github.com/viur-framework/viur-core/blob/7801292f664957202bc14756d1d51b9ff917343d/src/viur/core/bones/relational.py#L1102-L1103

fix: Return a `list` instead of `None` in `RelationalBone.relskels_from_keys`

---

src/viur/core/bones/select.py

Both had the same implementations, but different names and swapped descriptions

fix: Correct `translation_key_prefix_skeleton_bonename` and `translation_key_prefix_bonename`

---

src/viur/core/modules/translation.py

Allows to filter keys using an `fnmatch`-style pattern to keep request payload low.

feat: `pattern`-parameter for `Translation.get_public()`

---

src/viur/core/prototypes/list.py
src/viur/core/prototypes/skelmodule.py
src/viur/core/prototypes/tree.py
src/viur/core/render/html/env/viur.py

- fixes that `getList()` in Jinja-templates doesn't apply the default_order (fixes #1339)
- removes rendundant codebases
- I don't know why I didn't do it this way before?

fix: `SkelModule.default_order` generalized

---

src/viur/core/skeleton.py

Remove fromDB() and toDB() deprecation warnings for now?
I think it's still too early, especially because there are API changes that may lead to unwanted errors and breaking.
Pros:
- fromDB() and toDB() already use read() and write() internally
- API remains compatible
Cons:
- Projects may not be willing to change their API calls.

fix: Lower deprecations for `Skeleton.fromDB/toDB`

---

src/viur/core/bones/file.py
src/viur/core/modules/file.py

just add servingurl to default refkeys in filebone.
Enhancement for #1241.

fix: add `servingurl`  to `FileBone`s default `refKeys` setting

---

src/viur/core/request.py

You cannot use unsafe-inline and nonce together. Chrome refuses all styles otherwise.

fix: Don't create a CSP nonce if unsafe-inline is enabled

---

CHANGELOG.md
src/viur/core/modules/file.py
src/viur/core/prototypes/tree.py
src/viur/core/render/json/default.py
src/viur/core/skeleton.py
src/viur/core/version.py

- `Skeleton.read()` now allows to create an entry when not existing (Skeletonish replacement for db.GetOrInsert()`
- `Tree.rootnodeSkel()` with optional ensure-feature
- Deprecation of `Tree.ensureOwnModuleRootNode()`
- `File.FileNodeSkel` now contains a `public`-bone to identify public root nodes
- `File.getUploadURL()` checks against public-setting of the uploaded file and the repository given

feat: Public-files repos and improved rootnodes

---

src/viur/core/bones/file.py

An empty multi-lang `FileBone` has `None` values
```py
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/toolkit/importer/importable.py", line 616, in _convert_entry
assert skel.toDB(update_relations=updateRelations)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/core/skeleton.py", line 1193, in toDB
bone.postSavedHandler(skel, bone_name, key)
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/core/bones/file.py", line 224, in postSavedHandler
handleDerives(values[lang])
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/core/bones/file.py", line 217, in handleDerives
for val in values:  # Ensure derives getting build for each file …
```

fix: `FileBone.postSaveHandler` iterates over `None`

---

src/viur/core/prototypes/list.py
src/viur/core/prototypes/tree.py

Either the query must be valid, and in case a key is provided, the entry must be readable.

fix: Regression from `canView()` refactoring

---

src/viur/core/modules/file.py

`File.write()` didn't make serving_url injection.
Therefore, this refactoring is a much better solution.

fix: `FileLeafSkel._inject_serving_url()` is the better choice

---

src/viur/core/bones/base.py
src/viur/core/bones/file.py
src/viur/core/bones/record.py
src/viur/core/bones/relational.py
src/viur/core/tasks.py

The `postSavedHandler` of the `FileBone` inside a `RelSkel` (which is used as `UsingSkel` for a `RecordBone`) was never called. Therefore `ensureDerived` was never called for this bone too and derives are never generated.
Fixes #817

fix: Ensure derives are generated in `FileBone` inside a `RecordBone` too

---

src/viur/core/skeleton.py

The previous docstring caused InvalidEscapeSequence warnings with Python 3.12

doc: Fix `SyntaxWarning: invalid escape sequence '\*'`

---

src/viur/core/i18n.py
src/viur/core/render/html/env/viur.py

The problem was on the one hand that the path was first determined in `__str__`, which means that it is not the position where the translate object was created, but where it is converted to a string (this can also be in the renderer). I have therefore moved this to `__init__`.
Furthermore, the stack loaded in `walk_stack()` skipped too many frames (we actually need the first frame directly), so this couldn't work either -- except for Jinja. Now we load the stack explicitly from the top.

fix: determine a better path for a new `TranslateSkel`

---

src/viur/core/module.py

This speeds up the boot, since the `cached_property` isn't calculated during the boot, but lazily when it's needed.
And if you return a callable exposed via the cached_property you are just crazy :see_no_evil:

fix: skip `cached_property` in `Module._update_methods`

---

src/viur/core/prototypes/singleton.py
src/viur/core/prototypes/skelmodule.py
src/viur/core/prototypes/tree.py

This endpoint allows for an `add_or_edit`-action with the ability to provide a key as well. It is restricted to 'root'-users.

feat: Provide `add_or_edit` root-only endpoint for importers

---

src/viur/core/bones/base.py
src/viur/core/bones/string.py

The idea of _caseINSensitive_ bones is that the upper/lower case does not matter and `"Test"`, `"test"`, and `"TEST"` are equivalent.
If you now have a unique contstraint `UniqueLockMethod.SameValue`, it is still possible to create the three entries.
---
Alternatively, we could of course also introduce `UniqueLockMethod.EqualValue`, which controls this even more precisely.

fix: a `not caseSensitive` bone should lock the lower value

---

src/viur/core/bones/relational.py

Changes the error reporting
```
File "~/project/viur-core/src/viur/core/__init__.py", line 266, in setup
setSystemInitialized()
File "~/project/viur-core/src/viur/core/bones/base.py", line 44, in setSystemInitialized
skelCls.setSystemInitialized()
File "~/project/viur-core/src/viur/core/skeleton.py", line 553, in setSystemInitialized
bone.setSystemInitialized()
File "~/project/viur-core/src/viur/core/bones/relational.py", line 304, in setSystemInitialized
self._refSkelCache = RefSkel.fromSkel(self.kind, *self.refKeys)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/project/viur-core/src/viur/core/skeleton.py", line 1770, in fromSkel
fromSkel = skeletonByKind(kindName)
^^^^^^^^^^^^^^^^^^^^^^^^
File "~/project/viur-core/src/viur/core/skeleton.py", line 1835, in skeletonByKind
assert …
```

fix: Improve error reporting for unknown `RelationalBone` kinds

---

src/viur/core/__init__.py
src/viur/core/config.py
src/viur/core/email.py
src/viur/core/modules/user.py
src/viur/core/scripts/viur_migrate.py
src/viur/core/tasks.py

* Add name mapping in viur-migrate
* Rename calls in core itself

  fix: Email methods has been renamed

---

src/viur/core/modules/file.py

I monkey patched this name for testing and the error was confusing.

fix: Use variable instead of custom name joining for public bucket

---

src/viur/core/modules/file.py

`set_image_meta` fills the `width` and `height` bones of a `FileSkel` with the image dimensions.

feat: Add missing `onAdd` and `onAdded` calls in `File` module and implement `set_image_meta`

---

src/viur/core/bones/boolean.py
src/viur/core/skeleton.py

- Fixed `BooleanBone.refresh()` to respect a language setting
- Improved `BooleanBone.singleValueFromClient()` to use conf-values for booleans
- ~Fixed `Skeleton.write()` to not raise a catched Exception when it occurs (in this case, came from the resolved bug: Value of type bool is not iterable)~

fix: `BooleanBone.refresh()` doesn't respect language

---

src/viur/core/bones/file.py
src/viur/core/bones/relational.py

This is part of the "public-Files"-feature introduced with viur-core 3.7. In case of a RelationalBone configured as public, and an assigned image that is public but has no serving_url, the referenced entry should be refreshed as well.

fix: `FileBone.refresh()` should fix `serving_url`

---

src/viur/core/bones/__init__.py
src/viur/core/bones/base.py
src/viur/core/bones/sortindex.py
src/viur/core/prototypes/list.py
src/viur/core/prototypes/tree.py
src/viur/core/skeleton.py

Alternative solution for https://github.com/viur-framework/viur-core/pull/1399 to fix https://github.com/viur-framework/viur-core/issues/1385 and problem with clones unique bones

 feat: Implement `CloneBehavior` + `CloneStrategy` for a bone individual clone behavior

---

src/viur/core/modules/user.py
src/viur/core/tasks.py

fix: Load user in a deferred task

---

src/viur/core/bones/string.py
src/viur/core/modules/translation.py

* `tr_key` must be required, otherwise this makes no sense for mappings
* longer `translations` should be supported too
* `tr_key`, `translations` and `default_text` should not be HTML escaped, sometimes they contains links, or words that should be highlighted with e.g. `<strong/>`
* `tr_key`s are often longer than 50 char, but they should still be searchable
* Use custom `name` implementation, instead of the `key`. (E.g. used for tabs in admin)

fix: Make translations usable

---

src/viur/core/i18n.py

- evaluate the switch first in any conditions
- missing evaluation of `add_missing_translations` in {% translate ... %} constructs

fix: `conf.i18n.add_missing_translations` the right way

---

src/viur/core/config.py

The new config type has now been established in the core for two versions.  
In order to force all projects that are still running in compatibility mode to change over, I think it is a good opportunity to activate strict mode by default for 3.8. If necessary, it can of course still be explicitly deactivated.

chore: Enforce config strict mode

---

src/viur/core/bones/boolean.py

I have cases where it should be recognizable that an explicit selection was made and the value was provided in this way. To do this, I set the empty value to `None` (the default is `False` ...).
However, the `None` is discarded by the boolean casts.
```py
my_boolean = BooleanBone(
required=True,
getEmptyValueFunc=lambda *_, **__: None,
)
```

fix: Keep `None` in `BooleanBones`

---

src/viur/core/decorators.py
src/viur/core/module.py

- `Method.skey` must hold the entire skey_config, as it is used within `Method.__call__`
- `Method.additional_descr` should be set to "skey"-name and not "access" (copy&paste bug)
---
Originated from error:
```
[2025-02-19 11:34:06,036] /.../viur/core/request.py:375 [ERROR] ViUR has caught an unhandled exception!
[2025-02-19 11:34:06,037] /.../viur/core/request.py:376 [ERROR] string indices must be integers, not 'str'
File "~/viur-core/src/viur/core/request.py", line 350, in _process
File "~/viur-core/src/viur/core/request.py", line 632, in _route
File "~/viur-core/src/viur/core/module.py", line 199, in __call__
if self.skey and param_name == self.skey["forward_payload"]: …
```

fix: Hotfix for decorator `@skey` introduced by #1394

---

src/viur/core/modules/file.py

Pull request #1391 introduced this bug coming up when creating a FOLDER!
```
[2025-02-19 11:41:33,257] /.../viur/core/request.py:375 [ERROR] ViUR has caught an unhandled exception!
[2025-02-19 11:41:33,257] /.../viur/core/request.py:376 [ERROR] 'NoneType' object has no attribute 'startswith'
File "~/viur-core/src/viur/core/request.py", line 350, in _process
File "~/viur-core/src/viur/core/request.py", line 632, in _route
File "~/viur-core/src/viur/core/module.py", line 236, in __call__
return self._func(self._instance, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/viur-core/src/viur/core/modules/file.py", line 1214, in add
return super().add(skelType, …
```

fix: Hotfix for #1391: missing skeltype-check

---

src/viur/core/skeleton.py

Fixes two bugs:
1. `Skeleton.write()` returns another skeleton than the one that is passed. Especially when working with subskels, this is an unwanted behavior.
2. Due the previous full skeleton return, the `postSaveHandlers` of `RelationalBones` are ALL executed, also when the bone is not part of the skeleton. This yields in a query that is fired every time on every bone, which slows down the entire process of the write() with nonsense queries.

fix: `Skeleton.write()` returns full skeleton

---

src/viur/core/bones/numeric.py

This bug came in with the vi-admin 4.8.x which enforces client-side validation, also of the precision.
In case there of this bone definition
```python
timedrift = NumericBone(
descr="Zeitkorrektur",
defaultValue=0,
indexed=False,
precision=1
)
```
And a computed value that was -4.03169999999, the client rejected to submit the mask with
The problem here is, that the client enforces everything right, but the server loads the value -4.03169999999 which is not valid by its own bonedefinition, so -4.0 would be the correct value.
This pull request fixes NumericBone to store and load only values with the correct precision set.

fix: `NumericBone` ignores precision on read & write

---

src/viur/core/skeleton.py

This function is used rarely, and it makes sense to always obtain a sorted list of skeletons. As the function now also returns a list, it can be directly returned as sorted.
This affects, for example, callable tasks which provide a kind selector, like RebuildSearchIndex.

fix: Make `skeleton.listKnownSkeletons` always sorted

---

src/viur/core/config.py
src/viur/core/tasks.py

@CallDeferred tasks run in the Cloud Tasks Queue "default" by default. One way to run them in a different task queue is to use the `_queue` parameter when calling the task.
However, as this is not possible for existing or low-hanging calls, default values can be defined here for each task.
To do this, the task path must be mapped to the queue name:
```
conf.tasks_default_queues["updateRelations.viur.core.skeleton"] = "update_relations"
```
The queue (in the example: `"update_relations"`) must exist. The default queue can be changed by overwriting `"__default__"`.

feat: Implement `conf.tasks_default_queues`

---

src/viur/core/tasks.py

This code was around 12 years old and would already fail on the first statement: `db.Delete(currentTask.key())` (key is no longer a method...)
The counterpart does no longer exist; callableTasks are always executed direclty and decide on their own to call a `DeferredTask` or not.

chore: Remove legacy `viur-queued-tasks` code

---

src/viur/core/modules/file.py

This bug raised error.Gone() 410 when trying to rename a folder...

fix: `File.onEdit()` executes "leaf"-related stuff regardless of the `skelType`

---

src/viur/core/prototypes/list.py
src/viur/core/prototypes/singleton.py
src/viur/core/prototypes/skelmodule.py

This is a lighter version of #1384, integrating the feature only for `Singleton` and `List`.

feat: Evaluate `x-viur-bonelist` on default `viewSkel()` (light-version)

---

src/viur/core/config.py

Like #1411 
and make things for the admin and @akelch easier in the future

chore: Disable all compatibility flags by default

---

src/viur/core/bones/numeric.py
tests/bones/test_numeric_bone.py

PR #1425 introduced a `singleValueUnserialize` implementation that has no robustness against any other formats.
We still have old StringBone values in the database (`val={'val': '0.5', 'idx': '0.5'}`). This was never noticed, as there was never an error before. Now the value can neither be loaded nor ignored, nor does the `getDefaultValue` in except work without parameters. So no rebuild search index can be made with `refresh()` if the value is not loaded in the first place.

fix: `singleValueUnserialize` is now working more stable

---

CHANGELOG.md
src/viur/core/prototypes/skelmodule.py
src/viur/core/prototypes/tree.py
src/viur/core/version.py

Might corrupt data under special circumstances (in this case: translation-module)

fix: `add_or_edit` edits entries with empty skeleton

---

src/viur/core/bones/base.py
src/viur/core/bones/record.py

- Correctly parses, saves and reads RecordBones in RecordBones, fixes #1426
- Refactored code, removed unnecessary stuff that causes double unserialization
- Fixed `BaseBone.collectRawClientData()` to replace only the real prefix, and no other substrings which might contain the prefix

fix: `RecordBone` and prefix substitution

---

src/viur/core/bones/string.py

With this PR the value of a Stringbone is unescaped or escaped on an refresh depends on `escape_html`

feat: Apply `escape_html`-settings in `StringBone.refresh()` 

---

src/viur/core/modules/user.py

This PR fixes the following problem. When you edit a user, the user's session is not edited. This means, for example, that if you revoke a right from a user, the user retains this right until the session expires. Or if you add one, it only becomes usable when you log out and log in again.

fix: Update user's data in session on `user/edit`

---

src/viur/core/prototypes/list.py

fix: `prototypes.List` shall default to `addSkel` on cloning

---

src/viur/core/bones/password.py
src/viur/core/modules/user.py

- Sets all required fields to an invalid error
- Uses skel.fromClient() for LoginSkel to parse correct required fields
- Extends PasswordBone to optional raw-mode for LoginSkel
Replacement for #1479.

fix: Improve auth_userpassword login failure detection

---

src/viur/core/bones/base.py
src/viur/core/prototypes/singleton.py

So you can always get a skeleton regardless if it was saved before or not (and has only default values).

feat: Pass `create` param in `Singleton.getContents()` to `Skeleton.read()`

---

src/viur/core/skeleton/skeleton.py

Missed in https://github.com/viur-framework/viur-core/pull/1495 and https://github.com/viur-framework/viur-core/pull/1454

fix: Update skeleton write update relations

---

src/viur/core/db/query.py
src/viur/core/render/json/default.py
src/viur/core/skeleton/instance.py
src/viur/core/skeleton/utils.py
src/viur/core/tasks.py

- New `SkelList`-constructor
- Use `SkelList` correctly in _tasks/list
- Disallow use of non-skellist-values in render (this broke!)

fix+refactor: `_tasks/list` and `SkelList`

---

src/viur/core/request.py

This change made in #1504 currently means that I can no longer redirect to `#` routes in a Vue app... if I want to redirect to “/#/12345”, it turns the URL into /%23/12345... therefore `#` should become a safe char.

fix: Make `#` a safe character for redirects

---

src/viur/core/modules/history.py

Add 'changed_fields' to the 'History' module. This can be used when we want to filter the logs for specific changes to bones.
For example, if you want to list all log entries where the bone 'bar' has been changed.
```sql
SELECT  
*
FROM `foo-viur3.history.default`
WHERE EXISTS (
SELECT 1
FROM UNNEST(changed_fields) as fields
WHERE fields = "bar"
)
```

feat: Add `changed_fields` in `History`-Module

---

src/viur/core/modules/user.py

There are too many cases where a "system-built-in" "root"-flagging is performed. We now have projects where users who can administrate users aren't "root". This PR paves the way to allow project-dependent settings.
This change might lead into incompatibility with some projects regarding #1537.

fix: `User.is_admin()` to determine User admin privileges

---

src/viur/core/session.py

1. Convert `conf.user.session_life_time.total_seconds()` to `int`
2. Set `Session.use_session_cookie` to `False` default.
Max-Age was never in use by default because `Session.use_session_cookie` was set to `True`

fix: Cookie lifetime.

---

src/viur/core/modules/user.py

This change would allow the User.onLogin()-hook to update things in the provided UserSkel and take this (probably updated) UserSkel into the session. Otherwise, it might happen that the UserSkel is internally updated, but the old UserSkel remains in the session.
Here's an actual example for such a hook from a customer project (without code that does the `current.session.get()["user"]`-re-assignment and `current.user.set()`-call, which are necessary without this change):
```py
def onLogin(self, skel):
if not skel["manualoverride"] and skel["debitor"]:
ok, _ = conf.main_app.thirdparty.sync_user_skel(skel)
if ok:
skel.write(update_relations=False)
if not self.is_active(skel):
session.killSessionByUser(skel["key"])
raise errors.Redirect("s/user_locked")
super().onLogin(skel)
```

fix: `User.onLogin()` shall be called earlier
